class Paths {

  static readonly home='/'
  static readonly blockchain = '/blockchain-data'
  static readonly about='/about'
  static readonly overview='/overview'
  static readonly help='/help'
  static readonly writer='/create'
  static readonly reader='/read'
  static readonly orgWriter='/create-organisation'
  static readonly orgReportWriter='/create-organisation-report'
  static readonly orgReportBudgetsWriter = '/create-organisation-report-budget'
  static readonly orgReportExpenditureWriter = '/create-organisation-report-expenditure'
  static readonly orgReportRecipientBudgetsWriter = '/create-organisation-report-recipient-budget'
  static readonly orgReportRegionBudgetsWriter = '/create-organisation-report-region-budget'
  static readonly orgReader='/read-organisations'
  static readonly orgReportReader='/read-organisation-reports'
  static readonly orgReportBudgetsReader = '/read-organisation-report-budgets'
  static readonly orgReportExpenditureReader = '/read-organisation-report-expenditure'
  static readonly orgReportRecipientBudgetsReader = '/read-organisation-report-recipient-budgets'
  static readonly orgReportRegionBudgetsReader = '/read-organisation-report-region-budgets'
}

class Blockchain {

  // Using web3 via MetaMask, so these aren't necessary, really
  static readonly host = 'http://127.0.0.1'
  static readonly port = '8545'
  static readonly network = 'ropsten'

  static readonly checkInterval = 3000
}

class Contract {

  static organisationsABI = [
    "event SetOrganisation(bytes32 _orgRef, tuple(bytes32 orgRef, string name, string identifier) _org)",

    "function setOrganisation(tuple(bytes32 orgRef, string name, string identifier) _org)@150000",

    "function getOrganisationExists(bytes32 _orgRef) view returns (bool)",
    "function getNumOrganisations() view returns (uint256)",
    "function getOrganisationReference(uint256 _index) view returns (bytes32)",
    "function getOrganisation(bytes32 _orgRef) view returns (tuple(bytes32 orgRef, string name, string identifier) org)",
    "function getOrganisationName(bytes32 _orgRef) view returns (string)",
    "function getOrganisationIdentifier(bytes32 _orgRef) view returns (string)"
  ]

  static organisationReportsABI = [
    "event SetReport(bytes32 orgRef, bytes32 reportRef, tuple(bytes32 version, bytes32 orgRef, bytes32 reportRef, tuple(bytes32 orgRef, uint8 orgType, bool isSecondary) reportingOrg, bytes32 lang, bytes32 currency, bytes32 lastUpdatedTime) report)",

    "function setReport(tuple(bytes32 version, bytes32 orgRef, bytes32 reportRef, tuple(bytes32 orgRef, uint8 orgType, bool isSecondary) reportingOrg, bytes32 lang, bytes32 currency, bytes32 lastUpdatedTime) report)@500000",

    "function getOrgExists(bytes32 orgRef) view returns (bool)",
    "function getReportExists(bytes32 orgRef, bytes32 reportRef) view returns (bool)",

    "function getNumOrgs() view returns (uint256)",
    "function getNumReports(bytes32 orgRef) view returns (uint256)",

    "function getOrganisationReference(uint256 _index) view returns (bytes32)",
    "function getReportReference(bytes32 orgRef, uint256 index) view returns (bytes32)",

    "function getReport(bytes32 orgRef, bytes32 reportRef) view returns (tuple(bytes32 version, bytes32 orgRef, bytes32 reportRef, tuple(bytes32 orgRef, uint8 orgType, bool isSecondary) reportingOrg, bytes32 lang, bytes32 currency, bytes32 lastUpdatedTime) report)",

    "function getLang(bytes32 orgRef, bytes32 reportRef) view returns (bytes32)",
    "function getCurrency(bytes32 orgRef, bytes32 reportRef) view returns (bytes32)",
    "function getVersion(bytes32 orgRef, bytes32 reportRef) view returns (bytes32)",
    "function getLastUpdatedTime(bytes32 orgRef, bytes32 reportRef) view returns (bytes32)",
    "function getReportingOrg(bytes32 orgRef, bytes32 reportRef) view returns (bytes32)",
    "function getReportingOrgType(bytes32 orgRef, bytes32 reportRef) view returns (uint8)",
    "function getReportingOrgIsSecondary(bytes32 orgRef, bytes32 reportRef) view returns (bool)"
  ]

  static organisationReportDocsABI = [
    "event SetDocument(bytes32 reportRef, bytes32 docRef, tuple(bytes32 reportRef, bytes32 docRef, string title, bytes32 format, string url, bytes32 category, bytes32 countryCode, string desc, bytes32 lang, bytes32 date) doc)",

    "function setDocument(tuple(bytes32 reportRef, bytes32 docRef, string title, bytes32 format, string url, bytes32 category, bytes32 countryCode, string desc, bytes32 lang, bytes32 date) doc)@500000",

    "function getReportDocExists(bytes32 reportRef, bytes32 docRef) view returns (bool)",

    "function getNumReportDocs(bytes32 reportRef) view returns (uint256)",

    "function getReportDocReference(bytes32 docRef, uint256 index) view returns (bytes32)",

    "function getDocument(bytes32 reportRef, bytes32 docRef) view returns (tuple(bytes32 reportRef, bytes32 docRef, string title, bytes32 format, string url, bytes32 category, bytes32 countryCode, string desc, bytes32 lang, bytes32 date) doc)",

    "function getDocumentTitle(bytes32 reportRef, bytes32 docRef) view returns (string)",
    "function getDocumentFormat(bytes32 reportRef, bytes32 docRef) view returns (bytes32)",
    "function getDocumentURL(bytes32 reportRef, bytes32 docRef) view returns (string)",
    "function getDocumentCategory(bytes32 reportRef, bytes32 docRef) view returns (bytes32)",
    "function getDocumentCountry(bytes32 reportRef, bytes32 docRef) view returns (bytes32)",
    "function getDocumentDescription(bytes32 reportRef, bytes32 docRef) view returns (string)",
    "function getDocumentLang(bytes32 reportRef, bytes32 docRef) view returns (bytes32)",
    "function getDocumentDate(bytes32 reportRef, bytes32 docRef) view returns (bytes32)"
  ]

  static organisationReportBudgetsABI = [
    "event SetTotalBudget(bytes32 reportRef, bytes32 budgetRef, tuple(bytes32 reportRef, bytes32 budgetRef, bytes32 budgetLine, tuple(uint256 value, uint8 status, bytes32 start, bytes32 end) finance) budget)",

    "function setTotalBudget(tuple(bytes32 reportRef, bytes32 budgetRef, bytes32 budgetLine, tuple(uint256 value, uint8 status, bytes32 start, bytes32 end) finance) budget)@500000",

    "function getReportExists(bytes32 reportRef) view returns (bool)",
    "function getTotalBudgetExists(bytes32 reportRef, bytes32 budgetRef) view returns (bool)",

    "function getNumReports() view returns (uint256)",
    "function getNumTotalBudgets(bytes32 reportRef) view returns (uint256)",

    "function getReportReference(uint256 index) view returns (bytes32)",
    "function getTotalBudgetReference(bytes32 reportRef, uint256 index) view returns (bytes32)",

    "function getTotalBudget(bytes32 reportRef, bytes32 budgetRef) view returns (tuple(bytes32 reportRef, bytes32 budgetRef, bytes32 budgetLine, tuple(uint256 value, uint8 status, bytes32 start, bytes32 end) finance) budget)",
    "function getTotalBudgetLine(bytes32 reportRef, bytes32 budgetRef) view returns (bytes32)",
    "function getTotalBudgetValue(bytes32 reportRef, bytes32 budgetRef) view returns (uint256)",
    "function getTotalBudgetStatus(bytes32 reportRef, bytes32 budgetRef) view returns (uint8)",
    "function getTotalBudgetStart(bytes32 reportRef, bytes32 budgetRef) view returns (bytes32)",
    "function getTotalBudgetEnd(bytes32 reportRef, bytes32 budgetRef) view returns (bytes32)"
  ]

  static organisationReportExpenditureABI = [
    "event SetExpenditure(bytes32 reportRef, bytes32 expenditureRef, tuple(bytes32 reportRef, bytes32 expenditureRef, bytes32 expenditureLine, tuple(uint256 value, uint8 status, bytes32 start, bytes32 end) finance) expenditure)",

    "function setExpenditure(tuple(bytes32 reportRef, bytes32 expenditureRef, bytes32 expenditureLine, tuple(uint256 value, uint8 status, bytes32 start, bytes32 end) finance) expenditure)@500000",

    "function getReportExists(bytes32 reportRef) view returns (bool)",
    "function getExpenditureExists(bytes32 reportRef, bytes32 expenditureRef) view returns (bool)",

    "function getNumReports() view returns (uint256)",
    "function getNumExpenditures(bytes32 reportRef) view returns (uint256)",

    "function getReportReference(uint256 index) view returns (bytes32)",
    "function getExpenditureReference(bytes32 reportRef, uint256 index) view returns (bytes32)",

    "function getExpenditure(bytes32 reportRef, bytes32 expenditureRef) view returns (tuple(bytes32 reportRef, bytes32 expenditureRef, bytes32 expenditureLine, tuple(uint256 value, uint8 status, bytes32 start, bytes32 end) finance) expenditure)",
    "function getExpenditureLine(bytes32 reportRef, bytes32 budgetRef) view returns (bytes32)",
    "function getExpenditureValue(bytes32 reportRef, bytes32 expenditureRef) view returns (uint256)",
    "function getExpenditureStatus(bytes32 reportRef, bytes32 expenditureRef) view returns (uint8)",
    "function getExpenditureStart(bytes32 reportRef, bytes32 expenditureRef) view returns (bytes32)",
    "function getExpenditureEnd(bytes32 reportRef, bytes32 expenditureRef) view returns (bytes32)"
  ]

  static organisationReportRecipientBudgetsABI = [
    "event SetRecipientBudget(bytes32 _reportRef, bytes32 _budgetRef, tuple(bytes32 reportRef, bytes32 budgetRef, bytes32 orgRef, bytes32 budgetLine, tuple(uint256 value, uint8 status, bytes32 start, bytes32 end) finance) budget)",

    "function setRecipientBudget(tuple(bytes32 reportRef, bytes32 budgetRef, bytes32 orgRef, bytes32 budgetLine, tuple(uint256 value, uint8 status, bytes32 start, bytes32 end) finance) budget)@500000",

    "function getReportExists(bytes32 _reportRef) view returns (bool)",
    "function getRecipientBudgetExists(bytes32 _reportRef, bytes32 _budgetRef) view returns (bool)",

    "function getNumReports() view returns (uint256)",
    "function getNumRecipientBudgets(bytes32 _reportRef) view returns (uint256)",

    "function getReportReference(uint256 _index) view returns (bytes32)",
    "function getRecipientBudgetReference(bytes32 _reportRef, uint256 _index) view returns (bytes32)",

    "function getRecipientBudget(bytes32 _reportRef, bytes32 _recipientBudgetRef) view returns (tuple(bytes32 reportRef, bytes32 budgetRef, bytes32 orgRef, bytes32 budgetLine, tuple(uint256 value, uint8 status, bytes32 start, bytes32 end) finance) budget)",
    "function getRecipientBudgetOrg(bytes32 _reportRef, bytes32 _recipientBudgetRef) public view returns (bytes32)",
    "function getRecipientBudgetLine(bytes32 _reportRef, bytes32 _recipientBudgetRef) view returns (bytes32)",
    "function getRecipientBudgetValue(bytes32 _reportRef, bytes32 _recipientBudgetRef) view returns (uint256)",
    "function getRecipientBudgetStatus(bytes32 _reportRef, bytes32 _recipientBudgetRef) view returns (uint8)",
    "function getRecipientBudgetStart(bytes32 _reportRef, bytes32 _recipientBudgetRef) view returns (bytes32)",
    "function getRecipientBudgetEnd(bytes32 _reportRef, bytes32 _recipientBudgetRef) view returns (bytes32)"
  ]

  static organisationReportRegionBudgetsABI = [
    "event SetRegionBudget(bytes32 _reportRef, bytes32 _budgetRef, tuple(bytes32 reportRef, bytes32 budgetRef, uint256 regionRef, bytes32 budgetLine, tuple(uint256 value, uint8 status, bytes32 start, bytes32 end) finance) budget)",

    "function setRegionBudget(tuple(bytes32 reportRef, bytes32 budgetRef, uint256 regionRef, bytes32 budgetLine, tuple(uint256 value, uint8 status, bytes32 start, bytes32 end) finance) budget)@500000",

    "function getReportExists(bytes32 _reportRef) view returns (bool)",
    "function getRegionBudgetExists(bytes32 _reportRef, bytes32 _regionBudgetRef) view returns (bool)",

    "function getNumReports() view returns (uint256)",
    "function getNumRegionBudgets(bytes32 _reportRef) view returns (uint256)",

    "function getReportReference(uint256 _index) view returns (bytes32)",
    "function getRegionBudgetReference(bytes32 _reportRef, uint256 _index) view returns (bytes32)",

    "function getRegionsBudget(bytes32 _reportRef, bytes32 _regionBudgetRef) view returns (tuple(bytes32 reportRef, bytes32 budgetRef, uint256 regionRef, bytes32 budgetLine, tuple(uint256 value, uint8 status, bytes32 start, bytes32 end) finance) budget)",
    "function getRegionsBudgetRegion(bytes32 _reportRef, bytes32 _regionBudgetRef) public view returns (uint256)",
    "function getRegionsBudgetLine(bytes32 _reportRef, uint256 _regionBudgetRef) view returns (bytes32)",
    "function getRegionsBudgetValue(bytes32 _reportRef, bytes32 _regionBudgetRef) view returns (uint256)",
    "function getRegionsBudgetStatus(bytes32 _reportRef, bytes32 _regionBudgetRef) view returns (uint8)",
    "function getRegionsBudgetStart(bytes32 _reportRef, bytes32 _regionBudgetRef) view returns (bytes32)",
    "function getRegionsBudgetEnd(bytes32 _reportRef, bytes32 _regionBudgetRef) view returns (bytes32)"
  ]

  static organisationReportCountryBudgetsABI = [
    "event SetCountryBudget(bytes32 _reportRef, bytes32 _budgetRef, tuple(bytes32 reportRef, bytes32 budgetRef, bytes32 regionRef, bytes32 budgetLine, tuple(uint256 value, uint8 status, bytes32 start, bytes32 end) finance) budget)",

    "function setCountryBudget(tuple(bytes32 reportRef, bytes32 budgetRef, bytes32 countryRef, bytes32 budgetLine, tuple(uint256 value, uint8 status, bytes32 start, bytes32 end) finance) budget)@500000",

    "function getReportExists(bytes32 _reportRef) view returns (bool)",
    "function getCountryBudgetExists(bytes32 _reportRef, bytes32 _budgetRef) view returns (bool)",

    "function getNumReports() view returns (uint256)",
    "function getNumCountryBudgets(bytes32 _reportRef) view returns (uint256)",

    "function getReportReference(uint256 _index) view returns (bytes32)",
    "function getCountryBudgetReference(bytes32 _reportRef, uint256 _index) view returns (bytes32)",

    "function getCountryBudget(bytes32 _reportRef, bytes32 _countryBudgetRef) view returns (tuple(bytes32 reportRef, bytes32 budgetRef, bytes32 countryRef, bytes32 budgetLine, tuple(uint256 value, uint8 status, bytes32 start, bytes32 end) finance) budget)",
    "function getCountryBudgetCountry(bytes32 _reportRef, bytes32 _countryBudgetRef) view returns (bytes32)",
    "function getCountryBudgetLine(bytes32 _reportRef, bytes32 _countryBudgetRef) view returns (bytes32)",
    "function getCountryBudgetValue(bytes32 _reportRef, bytes32 _countryBudgetRef) view returns (uint256)",
    "function getCountryBudgetStatus(bytes32 _reportRef, bytes32 _countryBudgetRef) view returns (uint8)",
    "function getCountryBudgetStart(bytes32 _reportRef, bytes32 _countryBudgetRef) view returns (bytes32)",
    "function getCountryBudgetEnd(bytes32 _reportRef, bytes32 _countryBudgetRef) view returns (bytes32)"
  ]

  /* Ropsten addresses
  static organisationsAddress = "0x2C757C6390D9186F7e35C0796256B17d650df017"
  static organisationReportsAddress = "0x81759e5B8BCB38B05A678C2b98Eb17eaf4Ae9D71"
  */

  /*static organisationsAddress = "0x9ebE6568eb356a48E21b84e57e8b95da56Ad90Ab"
  static organisationReportsAddress = "0x8EC9d338E9F990B16cE873629C734FBC658a4Cac"
  static organisationReportDocsAddress = "0x8cA96cC847AE03c728d2d8957482B1FE113Ce810"
  static organisationReportBudgetsAddress = "0x1959a3B64A9b8a246cd4ae3305d29EF2Cf928358"
  static organisationReportExpenditureAddress = "0xC7271378FB6a2B8292d09Ba8637197c51fF4d26B"
  static organisationReportRecipientBudgetsAddress = "0xa5C039515f83982e33Da70210BD74c2a30a7Bd01"
  static organisationReportRegionBudgetsAddress = "0xc414e8AAbbe4753faBCf5180BD8438F99adb3016"
  static organisationReportCountryBudgetsAddress = "0xD63A6e29cc37e2A45ad723220c41dDB1AfC31Ec3"*/

  static organisationsAddress = "0x834ffE2EcA00e40C70f4242e41bdA0B0941a75d7"
  static organisationReportsAddress = "0x91283F4A2d54823B922fA7cF8c65017D7f5EdC13"
  static organisationReportDocsAddress = "0xadbc684Dbb5D931B72cED71C312EBcf3b56635B8"
  static organisationReportBudgetsAddress = "0x0b3EC01Dc3e538e32f444709E0725df09573a2f5"
  static organisationReportExpenditureAddress = "0xaC68282F256a82a5c50478F94364132cF3D0a3D8"
  static organisationReportRecipientBudgetsAddress = "0xAb14DDa441294c3679eAe7f051ca4751bc046bFF"
  static organisationReportRegionBudgetsAddress = "0xA651F65E1557E27b0a23Bd289171DC0c949F73Bc"
  static organisationReportCountryBudgetsAddress = "0x0Cf8AeA5B70FbD4DD18A11b8D381377FAc6F39FB"
}

class Helpers {

  static reportVersions = [
    { value: "2.03", label: "2.03" }
  ]

  static isSecondary = [
    { value: false, label: "No" },
    { value: true, label: "Yes" }
  ]

  static countryCodes = [
    {value: "AD", label: "AD"},
    {value: "AE", label: "AE"},
    {value: "AF", label: "AF"},
    {value: "AG", label: "AG"},
    {value: "AI", label: "AI"},
    {value: "AL", label: "AL"},
    {value: "AM", label: "AM"},
    {value: "AO", label: "AO"},
    {value: "AQ", label: "AQ"},
    {value: "AR", label: "AR"},
    {value: "AS", label: "AS"},
    {value: "AT", label: "AT"},
    {value: "AU", label: "AU"},
    {value: "AW", label: "AW"},
    {value: "AX", label: "AX"},
    {value: "AZ", label: "AZ"},
    {value: "BA", label: "BA"},
    {value: "BB", label: "BB"},
    {value: "BD", label: "BD"},
    {value: "BE", label: "BE"},
    {value: "BF", label: "BF"},
    {value: "BG", label: "BG"},
    {value: "BH", label: "BH"},
    {value: "BI", label: "BI"},
    {value: "BJ", label: "BJ"},
    {value: "BL", label: "BL"},
    {value: "BM", label: "BM"},
    {value: "BN", label: "BN"},
    {value: "BO", label: "BO"},
    {value: "BQ", label: "BQ"},
    {value: "BR", label: "BR"},
    {value: "BS", label: "BS"},
    {value: "BT", label: "BT"},
    {value: "BV", label: "BV"},
    {value: "BW", label: "BW"},
    {value: "BY", label: "BY"},
    {value: "BZ", label: "BZ"},
    {value: "CA", label: "CA"},
    {value: "CC", label: "CC"},
    {value: "CD", label: "CD"},
    {value: "CF", label: "CF"},
    {value: "CG", label: "CG"},
    {value: "CH", label: "CH"},
    {value: "CI", label: "CI"},
    {value: "CK", label: "CK"},
    {value: "CL", label: "CL"},
    {value: "CM", label: "CM"},
    {value: "CN", label: "CN"},
    {value: "CO", label: "CO"},
    {value: "CR", label: "CR"},
    {value: "CU", label: "CU"},
    {value: "CV", label: "CV"},
    {value: "CW", label: "CW"},
    {value: "CX", label: "CX"},
    {value: "CY", label: "CY"},
    {value: "CZ", label: "CZ"},
    {value: "DE", label: "DE"},
    {value: "DJ", label: "DJ"},
    {value: "DK", label: "DK"},
    {value: "DM", label: "DM"},
    {value: "DO", label: "DO"},
    {value: "DZ", label: "DZ"},
    {value: "EC", label: "EC"},
    {value: "EE", label: "EE"},
    {value: "EG", label: "EG"},
    {value: "EH", label: "EH"},
    {value: "ER", label: "ER"},
    {value: "ES", label: "ES"},
    {value: "ET", label: "ET"},
    {value: "FI", label: "FI"},
    {value: "FJ", label: "FJ"},
    {value: "FK", label: "FK"},
    {value: "FM", label: "FM"},
    {value: "FO", label: "FO"},
    {value: "FR", label: "FR"},
    {value: "GA", label: "GA"},
    {value: "GB", label: "GB"},
    {value: "GD", label: "GD"},
    {value: "GE", label: "GE"},
    {value: "GF", label: "GF"},
    {value: "GG", label: "GG"},
    {value: "GH", label: "GH"},
    {value: "GI", label: "GI"},
    {value: "GL", label: "GL"},
    {value: "GM", label: "GM"},
    {value: "GN", label: "GN"},
    {value: "GP", label: "GP"},
    {value: "GQ", label: "GQ"},
    {value: "GR", label: "GR"},
    {value: "GS", label: "GS"},
    {value: "GT", label: "GT"},
    {value: "GU", label: "GU"},
    {value: "GW", label: "GW"},
    {value: "GY", label: "GY"},
    {value: "HK", label: "HK"},
    {value: "HM", label: "HM"},
    {value: "HN", label: "HN"},
    {value: "HR", label: "HR"},
    {value: "HT", label: "HT"},
    {value: "HU", label: "HU"},
    {value: "ID", label: "ID"},
    {value: "IE", label: "IE"},
    {value: "IL", label: "IL"},
    {value: "IM", label: "IM"},
    {value: "IN", label: "IN"},
    {value: "IO", label: "IO"},
    {value: "IQ", label: "IQ"},
    {value: "IR", label: "IR"},
    {value: "IS", label: "IS"},
    {value: "IT", label: "IT"},
    {value: "JE", label: "JE"},
    {value: "JM", label: "JM"},
    {value: "JO", label: "JO"},
    {value: "JP", label: "JP"},
    {value: "KE", label: "KE"},
    {value: "KG", label: "KG"},
    {value: "KH", label: "KH"},
    {value: "KI", label: "KI"},
    {value: "KM", label: "KM"},
    {value: "KN", label: "KN"},
    {value: "KP", label: "KP"},
    {value: "KR", label: "KR"},
    {value: "KW", label: "KW"},
    {value: "KY", label: "KY"},
    {value: "KZ", label: "KZ"},
    {value: "LA", label: "LA"},
    {value: "LB", label: "LB"},
    {value: "LC", label: "LC"},
    {value: "LI", label: "LI"},
    {value: "LK", label: "LK"},
    {value: "LR", label: "LR"},
    {value: "LS", label: "LS"},
    {value: "LT", label: "LT"},
    {value: "LU", label: "LU"},
    {value: "LV", label: "LV"},
    {value: "LY", label: "LY"},
    {value: "MA", label: "MA"},
    {value: "MC", label: "MC"},
    {value: "MD", label: "MD"},
    {value: "ME", label: "ME"},
    {value: "MF", label: "MF"},
    {value: "MG", label: "MG"},
    {value: "MH", label: "MH"},
    {value: "MK", label: "MK"},
    {value: "ML", label: "ML"},
    {value: "MM", label: "MM"},
    {value: "MN", label: "MN"},
    {value: "MO", label: "MO"},
    {value: "MP", label: "MP"},
    {value: "MQ", label: "MQ"},
    {value: "MR", label: "MR"},
    {value: "MS", label: "MS"},
    {value: "MT", label: "MT"},
    {value: "MU", label: "MU"},
    {value: "MV", label: "MV"},
    {value: "MW", label: "MW"},
    {value: "MX", label: "MX"},
    {value: "MY", label: "MY"},
    {value: "MZ", label: "MZ"},
    {value: "NA", label: "NA"},
    {value: "NC", label: "NC"},
    {value: "NE", label: "NE"},
    {value: "NF", label: "NF"},
    {value: "NG", label: "NG"},
    {value: "NI", label: "NI"},
    {value: "NL", label: "NL"},
    {value: "NO", label: "NO"},
    {value: "NP", label: "NP"},
    {value: "NR", label: "NR"},
    {value: "NU", label: "NU"},
    {value: "NZ", label: "NZ"},
    {value: "OM", label: "OM"},
    {value: "PA", label: "PA"},
    {value: "PE", label: "PE"},
    {value: "PF", label: "PF"},
    {value: "PG", label: "PG"},
    {value: "PH", label: "PH"},
    {value: "PK", label: "PK"},
    {value: "PL", label: "PL"},
    {value: "PM", label: "PM"},
    {value: "PN", label: "PN"},
    {value: "PR", label: "PR"},
    {value: "PS", label: "PS"},
    {value: "PT", label: "PT"},
    {value: "PW", label: "PW"},
    {value: "PY", label: "PY"},
    {value: "QA", label: "QA"},
    {value: "RE", label: "RE"},
    {value: "RO", label: "RO"},
    {value: "RS", label: "RS"},
    {value: "RU", label: "RU"},
    {value: "RW", label: "RW"},
    {value: "SA", label: "SA"},
    {value: "SB", label: "SB"},
    {value: "SC", label: "SC"},
    {value: "SD", label: "SD"},
    {value: "SE", label: "SE"},
    {value: "SG", label: "SG"},
    {value: "SH", label: "SH"},
    {value: "SI", label: "SI"},
    {value: "SJ", label: "SJ"},
    {value: "SK", label: "SK"},
    {value: "SL", label: "SL"},
    {value: "SM", label: "SM"},
    {value: "SN", label: "SN"},
    {value: "SO", label: "SO"},
    {value: "SR", label: "SR"},
    {value: "SS", label: "SS"},
    {value: "ST", label: "ST"},
    {value: "SV", label: "SV"},
    {value: "SX", label: "SX"},
    {value: "SY", label: "SY"},
    {value: "SZ", label: "SZ"},
    {value: "TC", label: "TC"},
    {value: "TD", label: "TD"},
    {value: "TF", label: "TF"},
    {value: "TG", label: "TG"},
    {value: "TH", label: "TH"},
    {value: "TJ", label: "TJ"},
    {value: "TK", label: "TK"},
    {value: "TL", label: "TL"},
    {value: "TM", label: "TM"},
    {value: "TN", label: "TN"},
    {value: "TO", label: "TO"},
    {value: "TR", label: "TR"},
    {value: "TT", label: "TT"},
    {value: "TV", label: "TV"},
    {value: "TW", label: "TW"},
    {value: "TZ", label: "TZ"},
    {value: "UA", label: "UA"},
    {value: "UG", label: "UG"},
    {value: "UM", label: "UM"},
    {value: "US", label: "US"},
    {value: "UY", label: "UY"},
    {value: "UZ", label: "UZ"},
    {value: "VA", label: "VA"},
    {value: "VC", label: "VC"},
    {value: "VE", label: "VE"},
    {value: "VG", label: "VG"},
    {value: "VI", label: "VI"},
    {value: "VN", label: "VN"},
    {value: "VU", label: "VU"},
    {value: "WF", label: "WF"},
    {value: "WS", label: "WS"},
    {value: "YE", label: "YE"},
    {value: "YT", label: "YT"},
    {value: "ZA", label: "ZA"},
    {value: "ZM", label: "ZM"},
    {value: "ZW", label: "ZW"},
  ]

  static currencyCodes = [
    {value: "AED", label: "AED"},
    {value: "AFN", label: "AFN"},
    {value: "ALL", label: "ALL"},
    {value: "AMD", label: "AMD"},
    {value: "ANG", label: "ANG"},
    {value: "AOA", label: "AOA"},
    {value: "ARS", label: "ARS"},
    {value: "AUD", label: "AUD"},
    {value: "AWG", label: "AWG"},
    {value: "AZN", label: "AZN"},
    {value: "BAM", label: "BAM"},
    {value: "BBD", label: "BBD"},
    {value: "BDT", label: "BDT"},
    {value: "BGN", label: "BGN"},
    {value: "BHD", label: "BHD"},
    {value: "BIF", label: "BIF"},
    {value: "BMD", label: "BMD"},
    {value: "BND", label: "BND"},
    {value: "BOB", label: "BOB"},
    {value: "BRL", label: "BRL"},
    {value: "BSD", label: "BSD"},
    {value: "BTN", label: "BTN"},
    {value: "BWP", label: "BWP"},
    {value: "BYN", label: "BYN"},
    {value: "BZD", label: "BZD"},
    {value: "CAD", label: "CAD"},
    {value: "CDF", label: "CDF"},
    {value: "CHF", label: "CHF"},
    {value: "CLP", label: "CLP"},
    {value: "CNY", label: "CNY"},
    {value: "COP", label: "COP"},
    {value: "CRC", label: "CRC"},
    {value: "CUC", label: "CUC"},
    {value: "CUP", label: "CUP"},
    {value: "CVE", label: "CVE"},
    {value: "CZK", label: "CZK"},
    {value: "DJF", label: "DJF"},
    {value: "DKK", label: "DKK"},
    {value: "DOP", label: "DOP"},
    {value: "DZD", label: "DZD"},
    {value: "EGP", label: "EGP"},
    {value: "ERN", label: "ERN"},
    {value: "ETB", label: "ETB"},
    {value: "EUR", label: "EUR"},
    {value: "FJD", label: "FJD"},
    {value: "FKP", label: "FKP"},
    {value: "GBP", label: "GBP"},
    {value: "GEL", label: "GEL"},
    {value: "GGP", label: "GGP"},
    {value: "GHS", label: "GHS"},
    {value: "GIP", label: "GIP"},
    {value: "GMD", label: "GMD"},
    {value: "GNF", label: "GNF"},
    {value: "GTQ", label: "GTQ"},
    {value: "GYD", label: "GYD"},
    {value: "HKD", label: "HKD"},
    {value: "HNL", label: "HNL"},
    {value: "HRK", label: "HRK"},
    {value: "HTG", label: "HTG"},
    {value: "HUF", label: "HUF"},
    {value: "IDR", label: "IDR"},
    {value: "ILS", label: "ILS"},
    {value: "IMP", label: "IMP"},
    {value: "INR", label: "INR"},
    {value: "IQD", label: "IQD"},
    {value: "IRR", label: "IRR"},
    {value: "ISK", label: "ISK"},
    {value: "JEP", label: "JEP"},
    {value: "JMD", label: "JMD"},
    {value: "JOD", label: "JOD"},
    {value: "JPY", label: "JPY"},
    {value: "KES", label: "KES"},
    {value: "KGS", label: "KGS"},
    {value: "KHR", label: "KHR"},
    {value: "KMF", label: "KMF"},
    {value: "KPW", label: "KPW"},
    {value: "KRW", label: "KRW"},
    {value: "KWD", label: "KWD"},
    {value: "KYD", label: "KYD"},
    {value: "KZT", label: "KZT"},
    {value: "LAK", label: "LAK"},
    {value: "LBP", label: "LBP"},
    {value: "LKR", label: "LKR"},
    {value: "LRD", label: "LRD"},
    {value: "LSL", label: "LSL"},
    {value: "LYD", label: "LYD"},
    {value: "MAD", label: "MAD"},
    {value: "MDL", label: "MDL"},
    {value: "MGA", label: "MGA"},
    {value: "MKD", label: "MKD"},
    {value: "MMK", label: "MMK"},
    {value: "MNT", label: "MNT"},
    {value: "MOP", label: "MOP"},
    {value: "MRU", label: "MRU"},
    {value: "MUR", label: "MUR"},
    {value: "MVR", label: "MVR"},
    {value: "MWK", label: "MWK"},
    {value: "MXN", label: "MXN"},
    {value: "MYR", label: "MYR"},
    {value: "MZN", label: "MZN"},
    {value: "NAD", label: "NAD"},
    {value: "NGN", label: "NGN"},
    {value: "NIO", label: "NIO"},
    {value: "NOK", label: "NOK"},
    {value: "NPR", label: "NPR"},
    {value: "NZD", label: "NZD"},
    {value: "OMR", label: "OMR"},
    {value: "PAB", label: "PAB"},
    {value: "PEN", label: "PEN"},
    {value: "PGK", label: "PGK"},
    {value: "PHP", label: "PHP"},
    {value: "PKR", label: "PKR"},
    {value: "PLN", label: "PLN"},
    {value: "PYG", label: "PYG"},
    {value: "QAR", label: "QAR"},
    {value: "RON", label: "RON"},
    {value: "RSD", label: "RSD"},
    {value: "RUB", label: "RUB"},
    {value: "RWF", label: "RWF"},
    {value: "SAR", label: "SAR"},
    {value: "SBD", label: "SBD"},
    {value: "SCR", label: "SCR"},
    {value: "SDG", label: "SDG"},
    {value: "SEK", label: "SEK"},
    {value: "SGD", label: "SGD"},
    {value: "SHP", label: "SHP"},
    {value: "SLL", label: "SLL"},
    {value: "SOS", label: "SOS"},
    {value: "SPL*", label: "SPL*"},
    {value: "SRD", label: "SRD"},
    {value: "STN", label: "STN"},
    {value: "SVC", label: "SVC"},
    {value: "SYP", label: "SYP"},
    {value: "SZL", label: "SZL"},
    {value: "THB", label: "THB"},
    {value: "TJS", label: "TJS"},
    {value: "TMT", label: "TMT"},
    {value: "TND", label: "TND"},
    {value: "TOP", label: "TOP"},
    {value: "TRY", label: "TRY"},
    {value: "TTD", label: "TTD"},
    {value: "TVD", label: "TVD"},
    {value: "TWD", label: "TWD"},
    {value: "TZS", label: "TZS"},
    {value: "UAH", label: "UAH"},
    {value: "UGX", label: "UGX"},
    {value: "USD", label: "USD"},
    {value: "UYU", label: "UYU"},
    {value: "UZS", label: "UZS"},
    {value: "VEF", label: "VEF"},
    {value: "VND", label: "VND"},
    {value: "VUV", label: "VUV"},
    {value: "WST", label: "WST"},
    {value: "XAF", label: "XAF"},
    {value: "XCD", label: "XCD"},
    {value: "XDR", label: "XDR"},
    {value: "XOF", label: "XOF"},
    {value: "XPF", label: "XPF"},
    {value: "YER", label: "YER"},
    {value: "ZAR", label: "ZAR"},
    {value: "ZMW", label: "ZMW"},
    {value: "ZWD", label: "ZWD"}
  ]

  static organisationCodes = [
    {value: 10, label: "Government"},
    {value: 11, label: "Local Government"},
    {value: 15, label: "Other Public Sector"},
    {value: 21, label: "International NGO"},
    {value: 22, label: "National NGO"},
    {value: 23, label: "Regional NGO"},
    {value: 24, label: "Partner Country based NGO"},
    {value: 30, label: "Public Private Partnership"},
    {value: 40, label: "Multilateral"},
    {value: 60, label: "Foundation"},
    {value: 70, label: "Private Sector"},
    {value: 71, label: "Private Sector in Provider Country"},
    {value: 72, label: "Private Sector in Aid Recipient Country"},
    {value: 73, label: "Private Sector in Third Country"},
    {value: 80, label: "Academic, Training and Research"},
    {value: 90, label: "Other"}
  ]

  static oecdDacCrs = [
    {value: 1, label: "Austria"},
    {value: 2, label: "Belgium"},
    {value: 3, label: "Denmark"},
    {value: 4, label: "France"},
    {value: 5, label: "Germany"},
    {value: 6, label: "Italy"},
    {value: 7, label: "Netherlands"},
    {value: 8, label: "Norway"},
    {value: 9, label: "Portugal"},
    {value: 10, label: "Sweden"},
    {value: 11, label: "Switzerland"},
    {value: 12, label: "United Kingdom"},
    {value: 18, label: "Finland"},
    {value: 20, label: "Iceland"},
    {value: 21, label: "Ireland"},
    {value: 22, label: "Luxembourg"},
    {value: 30, label: "Cyprus"},
    {value: 40, label: "Greece"},
    {value: 45, label: "Malta"},
    {value: 50, label: "Spain"},
    {value: 55, label: "Turkey"},
    {value: 61, label: "Slovenia"},
    {value: 62, label: "Croatia"},
    {value: 68, label: "Czech Republic"},
    {value: 69, label: "Slovak Republic"},
    {value: 70, label: "Liechtenstein"},
    {value: 72, label: "Bulgaria"},
    {value: 75, label: "Hungary"},
    {value: 76, label: "Poland"},
    {value: 77, label: "Romania"},
    {value: 82, label: "Estonia"},
    {value: 83, label: "Latvia"},
    {value: 84, label: "Lithuania"},
    {value: 87, label: "Russia"},
    {value: 104, label: "Nordic Development Fund"},
    {value: 130, label: "Algeria"},
    {value: 133, label: "Libya"},
    {value: 301, label: "Canada"},
    {value: 302, label: "United States"},
    {value: 358, label: "Mexico"},
    {value: 543, label: "Iraq"},
    {value: 546, label: "Israel"},
    {value: 552, label: "Kuwait"},
    {value: 561, label: "Qatar"},
    {value: 566, label: "Saudi Arabia"},
    {value: 576, label: "United Arab Emirates"},
    {value: 611, label: "Azerbaijan"},
    {value: 613, label: "Kazakhstan"},
    {value: 701, label: "Japan"},
    {value: 732, label: "Chinese Taipei"},
    {value: 742, label: "Korea"},
    {value: 764, label: "Thailand"},
    {value: 765, label: "Timor-Leste"},
    {value: 801, label: "Australia"},
    {value: 807, label: "UNEP"},
    {value: 811, label: "Global Environment Facility"},
    {value: 812, label: "Montreal Protocol"},
    {value: 820, label: "New Zealand"},
    {value: 901, label: "International Bank for Reconstruction and Development"},
    {value: 902, label: "Multilateral Investment Guarantee Agency"},
    {value: 903, label: "International Finance Corporation"},
    {value: 905, label: "International Development Association"},
    {value: 906, label: "Caribbean Development Bank"},
    {value: 907, label: "International Monetary Fund"},
    {value: 909, label: "Inter-American Development Bank"},
    {value: 912, label: "IDB Special Fund"},
    {value: 913, label: "African Development Bank"},
    {value: 914, label: "African Development Fund"},
    {value: 915, label: "Asian Development Bank"},
    {value: 916, label: "AsDB Special Funds"},
    {value: 918, label: "EU Institutions"},
    {value: 921, label: "Arab Fund (AFESD)"},
    {value: 923, label: "UN Peacebuilding Fund"},
    {value: 926, label: "Council of Europe"},
    {value: 928, label: "World Health Organisation"},
    {value: 932, label: "Food and Agriculture Organisation"},
    {value: 940, label: "International Labour Organisation"},
    {value: 944, label: "International Atomic Energy Agency"},
    {value: 948, label: "UNECE"},
    {value: 951, label: "OPEC Fund for International Development"},
    {value: 952, label: "OAPEC"},
    {value: 953, label: "Arab Bank for Economic Development in Africa"},
    {value: 954, label: "Special Arab Aid Fund for Africa"},
    {value: 956, label: "IMF Trust Fund"},
    {value: 958, label: "IMF (Concessional Trust Funds)"},
    {value: 959, label: "UNDP"},
    {value: 960, label: "UNTA"},
    {value: 963, label: "UNICEF"},
    {value: 964, label: "UNRWA"},
    {value: 966, label: "WFP"},
    {value: 967, label: "UNHCR"},
    {value: 971, label: "UNAIDS"},
    {value: 974, label: "UNFPA"},
    {value: 976, label: "Islamic Development Bank"},
    {value: 978, label: "OSCE"},
    {value: 979, label: "Islamic Monetary Fund"},
    {value: 980, label: "Arab Fund for Technical Assistance to African and Arab Countries"},
    {value: 981, label: "Black Sea Trade & Development Bank"},
    {value: 982, label: "GODE"},
    {value: 983, label: "Other Arab Agencies"},
    {value: 988, label: "IFAD"},
    {value: 990, label: "European Bank for Reconstruction and Development"},
    {value: 992, label: "UN AGENCIES"},
    {value: 997, label: "Global Partnership for Education"},
    {value: 1011, label: "Climate Investment Funds"},
    {value: 1012, label: "Adaptation Fund"},
    {value: 1013, label: "Council of Europe Development Bank"},
    {value: 1014, label: "Private Infrastructure Development Group"},
    {value: 1015, label: "Development Bank of Latin America"},
    {value: 1016, label: "Green Climate Fund"},
    {value: 1017, label: "Credit Guarantee and Investment Facility"},
    {value: 1018, label: "Global Energy Efficiency and Renewable Energy Fund"},
    {value: 1019, label: "IDB Invest"},
    {value: 1020, label: "Central Emergency Response Fund"},
    {value: 1023, label: "World Tourism Organisation"},
    {value: 1024, label: "Asian Infrastructure Investment Bank"},
    {value: 1025, label: "Center of Excellence in Finance"},
    {value: 1311, label: "Global Alliance for Vaccines and Immunization"},
    {value: 1312, label: "Global Fund"},
    {value: 1313, label: "Global Green Growth Institute"},
    {value: 1601, label: "Bill & Melinda Gates Foundation"},
    {value: 1602, label: "Dutch Postcode Lottery"},
    {value: 1603, label: "Swedish Postcode Lottery"},
    {value: 1604, label: "People's Postcode Lottery"},
    {value: 1605, label: "MetLife Foundation"},
    {value: 1606, label: "MasterCard Foundation"},
    {value: 1607, label: "Grameen Crédit Agricole Foundation"},
    {value: 1608, label: "IKEA Foundation"},
    {value: 1609, label: "Bernard van Leer Foundation"},
    {value: 1610, label: "MAVA Foundation"},
    {value: 1611, label: "Oak Foundation"},
    {value: 1612, label: "H&M Foundation"},
    {value: 1613, label: "C&A Foundation"},
    {value: 1614, label: "Charity Projects Ltd (Comic Relief)"},
    {value: 1615, label: "Children's Investment Fund Foundation"},
    {value: 1616, label: "Gatsby Charitable Foundation"},
    {value: 1617, label: "Conrad N. Hilton Foundation"},
    {value: 1618, label: "David & Lucile Packard Foundation"},
    {value: 1619, label: "John D. & Catherine T. MacArthur Foundation"},
    {value: 1620, label: "Carnegie Corporation of New York"},
    {value: 1621, label: "Michael & Susan Dell Foundation"},
    {value: 1622, label: "Omidyar Network Fund, Inc."},
    {value: 1623, label: "Rockefeller Foundation"},
    {value: 1624, label: "William & Flora Hewlett Foundation"},
    {value: 1625, label: "Arcus Foundation"},
    {value: 1626, label: "Gordon and Betty Moore Foundation"},
    {value: 1627, label: "Ford Foundation"},
    {value: 1628, label: "Wellcome Trust"}
  ]

  static financeStatus = [
    {value: 1, label:	"Indicative"},
    {value: 2, label:	"Committed"}
  ]

  static days = [
    {value: 1, label: "1"},
    {value: 2, label: "2"},
    {value: 3, label: "3"},
    {value: 4, label: "4"},
    {value: 5, label: "5"},
    {value: 6, label: "6"},
    {value: 7, label: "7"},
    {value: 8, label: "8"},
    {value: 9, label: "9"},
    {value: 10, label: "10"},
    {value: 11, label: "11"},
    {value: 12, label: "12"},
    {value: 13, label: "13"},
    {value: 14, label: "14"},
    {value: 15, label: "15"},
    {value: 16, label: "16"},
    {value: 17, label: "17"},
    {value: 18, label: "18"},
    {value: 19, label: "19"},
    {value: 20, label: "20"},
    {value: 21, label: "21"},
    {value: 22, label: "22"},
    {value: 23, label: "23"},
    {value: 24, label: "24"},
    {value: 25, label: "25"},
    {value: 26, label: "26"},
    {value: 27, label: "27"},
    {value: 28, label: "28"},
    {value: 29, label: "29"},
    {value: 30, label: "30"},
    {value: 31, label: "31"}
  ]

  static months = [
    {value: 1, label: "January"},
    {value: 2, label: "February"},
    {value: 3, label: "March"},
    {value: 4, label: "April"},
    {value: 5, label: "May"},
    {value: 6, label: "June"},
    {value: 7, label: "July"},
    {value: 8, label: "August"},
    {value: 9, label: "September"},
    {value: 10, label: "October"},
    {value: 11, label: "November"},
    {value: 12, label: "December"}
  ]

  static years = [
    {value: 2000, label: "2000"},
    {value: 2001, label: "2001"},
    {value: 2002, label: "2002"},
    {value: 2003, label: "2003"},
    {value: 2004, label: "2004"},
    {value: 2005, label: "2005"},
    {value: 2006, label: "2006"},
    {value: 2007, label: "2007"},
    {value: 2008, label: "2008"},
    {value: 2009, label: "2009"},
    {value: 2010, label: "2010"},
    {value: 2011, label: "2011"},
    {value: 2012, label: "2012"},
    {value: 2013, label: "2013"},
    {value: 2014, label: "2014"},
    {value: 2015, label: "2015"},
    {value: 2016, label: "2016"},
    {value: 2017, label: "2017"},
    {value: 2018, label: "2018"},
    {value: 2019, label: "2019"},
    {value: 2020, label: "2020"},
    {value: 2021, label: "2021"},
    {value: 2022, label: "2022"},
    {value: 2023, label: "2023"},
    {value: 2024, label: "2024"},
    {value: 2025, label: "2025"},
    {value: 2026, label: "2026"},
    {value: 2027, label: "2027"},
    {value: 2028, label: "2028"},
    {value: 2029, label: "2029"},
    {value: 2030, label: "2030"},
    {value: 2031, label: "2031"},
    {value: 2032, label: "2032"},
    {value: 2033, label: "2033"},
    {value: 2034, label: "2034"},
    {value: 2035, label: "2035"},
    {value: 2036, label: "2036"},
    {value: 2037, label: "2037"},
    {value: 2038, label: "2038"},
    {value: 2039, label: "2039"},
    {value: 2040, label: "2040"}
  ]

}

export { Paths, Blockchain, Contract, Helpers }
