class Paths {

  static readonly home='/'
  static readonly blockchain = '/blockchain-data'
  static readonly about='/about'
  static readonly overview='/overview'
  static readonly help='/help'
  static readonly writer='/create'
  static readonly reader='/read'
  static readonly orgWriter='/create-organisation'
  static readonly orgReportWriter='/create-organisation-report'
  static readonly orgReportBudgetsWriter = '/create-organisation-report-budget'
  static readonly orgReportExpenditureWriter = '/create-organisation-report-expenditure'
  static readonly orgReportRecipientBudgetsWriter = '/create-organisation-report-recipient-budget'
  static readonly orgReportRegionBudgetsWriter = '/create-organisation-report-region-budget'
  static readonly orgReportCountryBudgetsWriter = '/create-organisation-report-country-budget'
  static readonly orgReader='/read-organisations'
  static readonly orgReportReader='/read-organisation-reports'
  static readonly orgReportBudgetsReader = '/read-organisation-report-budgets'
  static readonly orgReportExpenditureReader = '/read-organisation-report-expenditure'
  static readonly orgReportRecipientBudgetsReader = '/read-organisation-report-recipient-budgets'
  static readonly orgReportRegionBudgetsReader = '/read-organisation-report-region-budgets'
  static readonly orgReportCountryBudgetsReader = '/read-organisation-report-country-budgets'
}

class Blockchain {

  // Using web3 via MetaMask, so these aren't necessary, really
  static readonly host = 'http://127.0.0.1'
  static readonly port = '8545'
  static readonly network = 'ropsten'

  static readonly checkInterval = 3000
}

class Contract {

  static organisationsABI = [
    "event SetOrganisation(bytes32 _orgRef, tuple(bytes32 orgRef, string name, string identifier) _org)",

    "function setOrganisation(tuple(bytes32 orgRef, string name, string identifier) _org)@150000",

    "function getOrganisationExists(bytes32 _orgRef) view returns (bool)",
    "function getNumOrganisations() view returns (uint256)",
    "function getOrganisationReference(uint256 _index) view returns (bytes32)",
    "function getOrganisation(bytes32 _orgRef) view returns (tuple(bytes32 orgRef, string name, string identifier) org)",
    "function getOrganisationName(bytes32 _orgRef) view returns (string)",
    "function getOrganisationIdentifier(bytes32 _orgRef) view returns (string)"
  ]

  static organisationReportsABI = [
    "event SetReport(bytes32 orgRef, bytes32 reportRef, tuple(bytes32 version, bytes32 orgRef, bytes32 reportRef, tuple(bytes32 orgRef, uint8 orgType, bool isSecondary) reportingOrg, bytes32 lang, bytes32 currency, bytes32 lastUpdatedTime) report)",

    "function setReport(tuple(bytes32 version, bytes32 orgRef, bytes32 reportRef, tuple(bytes32 orgRef, uint8 orgType, bool isSecondary) reportingOrg, bytes32 lang, bytes32 currency, bytes32 lastUpdatedTime) report)@500000",

    "function getOrgExists(bytes32 orgRef) view returns (bool)",
    "function getReportExists(bytes32 orgRef, bytes32 reportRef) view returns (bool)",

    "function getNumOrgs() view returns (uint256)",
    "function getNumReports(bytes32 orgRef) view returns (uint256)",

    "function getOrganisationReference(uint256 _index) view returns (bytes32)",
    "function getReportReference(bytes32 orgRef, uint256 index) view returns (bytes32)",

    "function getReport(bytes32 orgRef, bytes32 reportRef) view returns (tuple(bytes32 version, bytes32 orgRef, bytes32 reportRef, tuple(bytes32 orgRef, uint8 orgType, bool isSecondary) reportingOrg, bytes32 lang, bytes32 currency, bytes32 lastUpdatedTime) report)",

    "function getLang(bytes32 orgRef, bytes32 reportRef) view returns (bytes32)",
    "function getCurrency(bytes32 orgRef, bytes32 reportRef) view returns (bytes32)",
    "function getVersion(bytes32 orgRef, bytes32 reportRef) view returns (bytes32)",
    "function getLastUpdatedTime(bytes32 orgRef, bytes32 reportRef) view returns (bytes32)",
    "function getReportingOrg(bytes32 orgRef, bytes32 reportRef) view returns (bytes32)",
    "function getReportingOrgType(bytes32 orgRef, bytes32 reportRef) view returns (uint8)",
    "function getReportingOrgIsSecondary(bytes32 orgRef, bytes32 reportRef) view returns (bool)"
  ]

  static organisationReportDocsABI = [
    "event SetDocument(bytes32 reportRef, bytes32 docRef, tuple(bytes32 reportRef, bytes32 docRef, string title, bytes32 format, string url, bytes32 category, bytes32 countryCode, string desc, bytes32 lang, bytes32 date) doc)",

    "function setDocument(tuple(bytes32 reportRef, bytes32 docRef, string title, bytes32 format, string url, bytes32 category, bytes32 countryCode, string desc, bytes32 lang, bytes32 date) doc)@500000",

    "function getReportDocExists(bytes32 reportRef, bytes32 docRef) view returns (bool)",

    "function getNumReportDocs(bytes32 reportRef) view returns (uint256)",

    "function getReportDocReference(bytes32 docRef, uint256 index) view returns (bytes32)",

    "function getDocument(bytes32 reportRef, bytes32 docRef) view returns (tuple(bytes32 reportRef, bytes32 docRef, string title, bytes32 format, string url, bytes32 category, bytes32 countryCode, string desc, bytes32 lang, bytes32 date) doc)",

    "function getDocumentTitle(bytes32 reportRef, bytes32 docRef) view returns (string)",
    "function getDocumentFormat(bytes32 reportRef, bytes32 docRef) view returns (bytes32)",
    "function getDocumentURL(bytes32 reportRef, bytes32 docRef) view returns (string)",
    "function getDocumentCategory(bytes32 reportRef, bytes32 docRef) view returns (bytes32)",
    "function getDocumentCountry(bytes32 reportRef, bytes32 docRef) view returns (bytes32)",
    "function getDocumentDescription(bytes32 reportRef, bytes32 docRef) view returns (string)",
    "function getDocumentLang(bytes32 reportRef, bytes32 docRef) view returns (bytes32)",
    "function getDocumentDate(bytes32 reportRef, bytes32 docRef) view returns (bytes32)"
  ]

  static organisationReportBudgetsABI = [
    "event SetTotalBudget(bytes32 reportRef, bytes32 budgetRef, tuple(bytes32 reportRef, bytes32 budgetRef, bytes32 budgetLine, tuple(uint256 value, uint8 status, bytes32 start, bytes32 end) finance) budget)",

    "function setTotalBudget(tuple(bytes32 reportRef, bytes32 budgetRef, bytes32 budgetLine, tuple(uint256 value, uint8 status, bytes32 start, bytes32 end) finance) budget)@500000",

    "function getReportExists(bytes32 reportRef) view returns (bool)",
    "function getTotalBudgetExists(bytes32 reportRef, bytes32 budgetRef) view returns (bool)",

    "function getNumReports() view returns (uint256)",
    "function getNumTotalBudgets(bytes32 reportRef) view returns (uint256)",

    "function getReportReference(uint256 index) view returns (bytes32)",
    "function getTotalBudgetReference(bytes32 reportRef, uint256 index) view returns (bytes32)",

    "function getTotalBudget(bytes32 reportRef, bytes32 budgetRef) view returns (tuple(bytes32 reportRef, bytes32 budgetRef, bytes32 budgetLine, tuple(uint256 value, uint8 status, bytes32 start, bytes32 end) finance) budget)",
    "function getTotalBudgetLine(bytes32 reportRef, bytes32 budgetRef) view returns (bytes32)",
    "function getTotalBudgetValue(bytes32 reportRef, bytes32 budgetRef) view returns (uint256)",
    "function getTotalBudgetStatus(bytes32 reportRef, bytes32 budgetRef) view returns (uint8)",
    "function getTotalBudgetStart(bytes32 reportRef, bytes32 budgetRef) view returns (bytes32)",
    "function getTotalBudgetEnd(bytes32 reportRef, bytes32 budgetRef) view returns (bytes32)"
  ]

  static organisationReportExpenditureABI = [
    "event SetExpenditure(bytes32 reportRef, bytes32 expenditureRef, tuple(bytes32 reportRef, bytes32 expenditureRef, bytes32 expenditureLine, tuple(uint256 value, uint8 status, bytes32 start, bytes32 end) finance) expenditure)",

    "function setExpenditure(tuple(bytes32 reportRef, bytes32 expenditureRef, bytes32 expenditureLine, tuple(uint256 value, uint8 status, bytes32 start, bytes32 end) finance) expenditure)@500000",

    "function getReportExists(bytes32 reportRef) view returns (bool)",
    "function getExpenditureExists(bytes32 reportRef, bytes32 expenditureRef) view returns (bool)",

    "function getNumReports() view returns (uint256)",
    "function getNumExpenditures(bytes32 reportRef) view returns (uint256)",

    "function getReportReference(uint256 index) view returns (bytes32)",
    "function getExpenditureReference(bytes32 reportRef, uint256 index) view returns (bytes32)",

    "function getExpenditure(bytes32 reportRef, bytes32 expenditureRef) view returns (tuple(bytes32 reportRef, bytes32 expenditureRef, bytes32 expenditureLine, tuple(uint256 value, uint8 status, bytes32 start, bytes32 end) finance) expenditure)",
    "function getExpenditureLine(bytes32 reportRef, bytes32 budgetRef) view returns (bytes32)",
    "function getExpenditureValue(bytes32 reportRef, bytes32 expenditureRef) view returns (uint256)",
    "function getExpenditureStatus(bytes32 reportRef, bytes32 expenditureRef) view returns (uint8)",
    "function getExpenditureStart(bytes32 reportRef, bytes32 expenditureRef) view returns (bytes32)",
    "function getExpenditureEnd(bytes32 reportRef, bytes32 expenditureRef) view returns (bytes32)"
  ]

  static organisationReportRecipientBudgetsABI = [
    "event SetRecipientBudget(bytes32 _reportRef, bytes32 _budgetRef, tuple(bytes32 reportRef, bytes32 budgetRef, bytes32 orgRef, bytes32 budgetLine, tuple(uint256 value, uint8 status, bytes32 start, bytes32 end) finance) budget)",

    "function setRecipientBudget(tuple(bytes32 reportRef, bytes32 budgetRef, bytes32 orgRef, bytes32 budgetLine, tuple(uint256 value, uint8 status, bytes32 start, bytes32 end) finance) budget)@500000",

    "function getReportExists(bytes32 _reportRef) view returns (bool)",
    "function getRecipientBudgetExists(bytes32 _reportRef, bytes32 _budgetRef) view returns (bool)",

    "function getNumReports() view returns (uint256)",
    "function getNumRecipientBudgets(bytes32 _reportRef) view returns (uint256)",

    "function getReportReference(uint256 _index) view returns (bytes32)",
    "function getRecipientBudgetReference(bytes32 _reportRef, uint256 _index) view returns (bytes32)",

    "function getRecipientBudget(bytes32 _reportRef, bytes32 _recipientBudgetRef) view returns (tuple(bytes32 reportRef, bytes32 budgetRef, bytes32 orgRef, bytes32 budgetLine, tuple(uint256 value, uint8 status, bytes32 start, bytes32 end) finance) budget)",
    "function getRecipientBudgetOrg(bytes32 _reportRef, bytes32 _recipientBudgetRef) public view returns (bytes32)",
    "function getRecipientBudgetLine(bytes32 _reportRef, bytes32 _recipientBudgetRef) view returns (bytes32)",
    "function getRecipientBudgetValue(bytes32 _reportRef, bytes32 _recipientBudgetRef) view returns (uint256)",
    "function getRecipientBudgetStatus(bytes32 _reportRef, bytes32 _recipientBudgetRef) view returns (uint8)",
    "function getRecipientBudgetStart(bytes32 _reportRef, bytes32 _recipientBudgetRef) view returns (bytes32)",
    "function getRecipientBudgetEnd(bytes32 _reportRef, bytes32 _recipientBudgetRef) view returns (bytes32)"
  ]

  static organisationReportRegionBudgetsABI = [
    "event SetRegionBudget(bytes32 _reportRef, bytes32 _budgetRef, tuple(bytes32 reportRef, bytes32 budgetRef, uint256 regionRef, bytes32 budgetLine, tuple(uint256 value, uint8 status, bytes32 start, bytes32 end) finance) budget)",

    "function setRegionBudget(tuple(bytes32 reportRef, bytes32 budgetRef, uint256 regionRef, bytes32 budgetLine, tuple(uint256 value, uint8 status, bytes32 start, bytes32 end) finance) budget)@500000",

    "function getReportExists(bytes32 _reportRef) view returns (bool)",
    "function getRegionBudgetExists(bytes32 _reportRef, bytes32 _regionBudgetRef) view returns (bool)",

    "function getNumReports() view returns (uint256)",
    "function getNumRegionBudgets(bytes32 _reportRef) view returns (uint256)",

    "function getReportReference(uint256 _index) view returns (bytes32)",
    "function getRegionBudgetReference(bytes32 _reportRef, uint256 _index) view returns (bytes32)",

    "function getRegionsBudget(bytes32 _reportRef, bytes32 _regionBudgetRef) view returns (tuple(bytes32 reportRef, bytes32 budgetRef, uint256 regionRef, bytes32 budgetLine, tuple(uint256 value, uint8 status, bytes32 start, bytes32 end) finance) budget)",
    "function getRegionsBudgetRegion(bytes32 _reportRef, bytes32 _regionBudgetRef) public view returns (uint256)",
    "function getRegionsBudgetLine(bytes32 _reportRef, uint256 _regionBudgetRef) view returns (bytes32)",
    "function getRegionsBudgetValue(bytes32 _reportRef, bytes32 _regionBudgetRef) view returns (uint256)",
    "function getRegionsBudgetStatus(bytes32 _reportRef, bytes32 _regionBudgetRef) view returns (uint8)",
    "function getRegionsBudgetStart(bytes32 _reportRef, bytes32 _regionBudgetRef) view returns (bytes32)",
    "function getRegionsBudgetEnd(bytes32 _reportRef, bytes32 _regionBudgetRef) view returns (bytes32)"
  ]

  static organisationReportCountryBudgetsABI = [
    "event SetCountryBudget(bytes32 _reportRef, bytes32 _budgetRef, tuple(bytes32 reportRef, bytes32 budgetRef, bytes32 regionRef, bytes32 budgetLine, tuple(uint256 value, uint8 status, bytes32 start, bytes32 end) finance) budget)",

    "function setCountryBudget(tuple(bytes32 reportRef, bytes32 budgetRef, bytes32 countryRef, bytes32 budgetLine, tuple(uint256 value, uint8 status, bytes32 start, bytes32 end) finance) budget)@500000",

    "function getReportExists(bytes32 _reportRef) view returns (bool)",
    "function getCountryBudgetExists(bytes32 _reportRef, bytes32 _budgetRef) view returns (bool)",

    "function getNumReports() view returns (uint256)",
    "function getNumCountryBudgets(bytes32 _reportRef) view returns (uint256)",

    "function getReportReference(uint256 _index) view returns (bytes32)",
    "function getCountryBudgetReference(bytes32 _reportRef, uint256 _index) view returns (bytes32)",

    "function getCountryBudget(bytes32 _reportRef, bytes32 _countryBudgetRef) view returns (tuple(bytes32 reportRef, bytes32 budgetRef, bytes32 countryRef, bytes32 budgetLine, tuple(uint256 value, uint8 status, bytes32 start, bytes32 end) finance) budget)",
    "function getCountryBudgetCountry(bytes32 _reportRef, bytes32 _countryBudgetRef) view returns (bytes32)",
    "function getCountryBudgetLine(bytes32 _reportRef, bytes32 _countryBudgetRef) view returns (bytes32)",
    "function getCountryBudgetValue(bytes32 _reportRef, bytes32 _countryBudgetRef) view returns (uint256)",
    "function getCountryBudgetStatus(bytes32 _reportRef, bytes32 _countryBudgetRef) view returns (uint8)",
    "function getCountryBudgetStart(bytes32 _reportRef, bytes32 _countryBudgetRef) view returns (bytes32)",
    "function getCountryBudgetEnd(bytes32 _reportRef, bytes32 _countryBudgetRef) view returns (bytes32)"
  ]

  /* Ropsten addresses
  static organisationsAddress = "0x2C757C6390D9186F7e35C0796256B17d650df017"
  static organisationReportsAddress = "0x81759e5B8BCB38B05A678C2b98Eb17eaf4Ae9D71"
  */

  /*static organisationsAddress = "0x9ebE6568eb356a48E21b84e57e8b95da56Ad90Ab"
  static organisationReportsAddress = "0x8EC9d338E9F990B16cE873629C734FBC658a4Cac"
  static organisationReportDocsAddress = "0x8cA96cC847AE03c728d2d8957482B1FE113Ce810"
  static organisationReportBudgetsAddress = "0x1959a3B64A9b8a246cd4ae3305d29EF2Cf928358"
  static organisationReportExpenditureAddress = "0xC7271378FB6a2B8292d09Ba8637197c51fF4d26B"
  static organisationReportRecipientBudgetsAddress = "0xa5C039515f83982e33Da70210BD74c2a30a7Bd01"
  static organisationReportRegionBudgetsAddress = "0xc414e8AAbbe4753faBCf5180BD8438F99adb3016"
  static organisationReportCountryBudgetsAddress = "0xD63A6e29cc37e2A45ad723220c41dDB1AfC31Ec3"*/

  static organisationsAddress = "0x834ffE2EcA00e40C70f4242e41bdA0B0941a75d7"
  static organisationReportsAddress = "0x91283F4A2d54823B922fA7cF8c65017D7f5EdC13"
  static organisationReportDocsAddress = "0xadbc684Dbb5D931B72cED71C312EBcf3b56635B8"
  static organisationReportBudgetsAddress = "0x0b3EC01Dc3e538e32f444709E0725df09573a2f5"
  static organisationReportExpenditureAddress = "0xaC68282F256a82a5c50478F94364132cF3D0a3D8"
  static organisationReportRecipientBudgetsAddress = "0xAb14DDa441294c3679eAe7f051ca4751bc046bFF"
  static organisationReportRegionBudgetsAddress = "0xA651F65E1557E27b0a23Bd289171DC0c949F73Bc"
  static organisationReportCountryBudgetsAddress = "0x0Cf8AeA5B70FbD4DD18A11b8D381377FAc6F39FB"
}

class Helpers {

  static reportVersions = [
    { value: "2.03", label: "2.03" }
  ]

  static isSecondary = [
    { value: false, label: "No" },
    { value: true, label: "Yes" }
  ]

  static currencyCodes = [
    {value: "AFN", label: "Afghanistan Afghani"},
    {value: "ALL", label: "Albania Lek"},
    {value: "DZD", label: "Algeria Dinar"},
    {value: "AOA", label: "Angola Kwanza"},
    {value: "ARS", label: "Argentina Peso"},
    {value: "AMD", label: "Armenia Dram"},
    {value: "AWG", label: "Aruba Guilder"},
    {value: "AUD", label: "Australia Dollar"},
    {value: "AZN", label: "Azerbaijan Manat"},
    {value: "BSD", label: "Bahamas Dollar"},
    {value: "BHD", label: "Bahrain Dinar"},
    {value: "BDT", label: "Bangladesh Taka"},
    {value: "BBD", label: "Barbados Dollar"},
    {value: "BYN", label: "Belarus Ruble"},
    {value: "BZD", label: "Belize Dollar"},
    {value: "BMD", label: "Bermuda Dollar"},
    {value: "BTN", label: "Bhutan Ngultrum"},
    {value: "BOB", label: "Bolivia Bolíviano"},
    {value: "BAM", label: "Bosnia and Herzegovina Convertible Marka"},
    {value: "BWP", label: "Botswana Pula"},
    {value: "BRL", label: "Brazil Real"},
    {value: "BND", label: "Brunei Darussalam Dollar"},
    {value: "BGN", label: "Bulgaria Lev"},
    {value: "BIF", label: "Burundi Franc"},
    {value: "KHR", label: "Cambodia Riel"},
    {value: "CAD", label: "Canada Dollar"},
    {value: "CVE", label: "Cape Verde Escudo"},
    {value: "KYD", label: "Cayman Islands Dollar"},
    {value: "CLP", label: "Chile Peso"},
    {value: "CNY", label: "China Yuan Renminbi"},
    {value: "COP", label: "Colombia Peso"},
    {value: "XOF", label: "Communauté Financière Africaine (BCEAO) Franc"},
    {value: "XAF", label: "Communauté Financière Africaine (BEAC) CFA Franc BEAC"},
    {value: "KMF", label: "Comorian Franc"},
    {value: "XPF", label: "Comptoirs Français du Pacifique (CFP) Franc"},
    {value: "CDF", label: "Congo/Kinshasa Franc"},
    {value: "CRC", label: "Costa Rica Colon"},
    {value: "HRK", label: "Croatia Kuna"},
    {value: "CUC", label: "Cuba Convertible Peso"},
    {value: "CUP", label: "Cuba Peso"},
    {value: "CZK", label: "Czech Republic Koruna"},
    {value: "DKK", label: "Denmark Krone"},
    {value: "DJF", label: "Djibouti Franc"},
    {value: "DOP", label: "Dominican Republic Peso"},
    {value: "XCD", label: "East Caribbean Dollar"},
    {value: "EGP", label: "Egypt Pound"},
    {value: "SVC", label: "El Salvador Colon"},
    {value: "ERN", label: "Eritrea Nakfa"},
    {value: "SZL", label: "eSwatini Lilangeni"},
    {value: "ETB", label: "Ethiopia Birr"},
    {value: "EUR", label: "Euro Member Countries"},
    {value: "FKP", label: "Falkland Islands (Malvinas) Pound"},
    {value: "FJD", label: "Fiji Dollar"},
    {value: "GMD", label: "Gambia Dalasi"},
    {value: "GEL", label: "Georgia Lari"},
    {value: "GHS", label: "Ghana Cedi"},
    {value: "GIP", label: "Gibraltar Pound"},
    {value: "GTQ", label: "Guatemala Quetzal"},
    {value: "GGP", label: "Guernsey Pound"},
    {value: "GNF", label: "Guinea Franc"},
    {value: "GYD", label: "Guyana Dollar"},
    {value: "HTG", label: "Haiti Gourde"},
    {value: "HNL", label: "Honduras Lempira"},
    {value: "HKD", label: "Hong Kong Dollar"},
    {value: "HUF", label: "Hungary Forint"},
    {value: "ISK", label: "Iceland Krona"},
    {value: "INR", label: "India Rupee"},
    {value: "IDR", label: "Indonesia Rupiah"},
    {value: "XDR", label: "International Monetary Fund (IMF) Special Drawing Rights"},
    {value: "IRR", label: "Iran Rial"},
    {value: "IQD", label: "Iraq Dinar"},
    {value: "IMP", label: "Isle of Man Pound"},
    {value: "ILS", label: "Israel Shekel"},
    {value: "JMD", label: "Jamaica Dollar"},
    {value: "JPY", label: "Japan Yen"},
    {value: "JEP", label: "Jersey Pound"},
    {value: "JOD", label: "Jordan Dinar"},
    {value: "KZT", label: "Kazakhstan Tenge"},
    {value: "KES", label: "Kenya Shilling"},
    {value: "KPW", label: "Korea (North) Won"},
    {value: "KRW", label: "Korea (South) Won"},
    {value: "KWD", label: "Kuwait Dinar"},
    {value: "KGS", label: "Kyrgyzstan Som"},
    {value: "LAK", label: "Laos Kip"},
    {value: "LBP", label: "Lebanon Pound"},
    {value: "LSL", label: "Lesotho Loti"},
    {value: "LRD", label: "Liberia Dollar"},
    {value: "LYD", label: "Libya Dinar"},
    {value: "MOP", label: "Macau Pataca"},
    {value: "MKD", label: "Macedonia Denar"},
    {value: "MGA", label: "Madagascar Ariary"},
    {value: "MWK", label: "Malawi Kwacha"},
    {value: "MYR", label: "Malaysia Ringgit"},
    {value: "MVR", label: "Maldives (Maldive Islands) Rufiyaa"},
    {value: "MRU", label: "Mauritania Ouguiya"},
    {value: "MUR", label: "Mauritius Rupee"},
    {value: "MXN", label: "Mexico Peso"},
    {value: "MDL", label: "Moldova Leu"},
    {value: "MNT", label: "Mongolia Tughrik"},
    {value: "MAD", label: "Morocco Dirham"},
    {value: "MZN", label: "Mozambique Metical"},
    {value: "MMK", label: "Myanmar (Burma) Kyat"},
    {value: "NAD", label: "Namibia Dollar"},
    {value: "NPR", label: "Nepal Rupee"},
    {value: "ANG", label: "Netherlands Antilles Guilder"},
    {value: "NZD", label: "New Zealand Dollar"},
    {value: "NIO", label: "Nicaragua Cordoba"},
    {value: "NGN", label: "Nigeria Naira"},
    {value: "NOK", label: "Norway Krone"},
    {value: "OMR", label: "Oman Rial"},
    {value: "PKR", label: "Pakistan Rupee"},
    {value: "PAB", label: "Panama Balboa"},
    {value: "PGK", label: "Papua New Guinea Kina"},
    {value: "PYG", label: "Paraguay Guarani"},
    {value: "PEN", label: "Peru Sol"},
    {value: "PHP", label: "Philippines Peso"},
    {value: "PLN", label: "Poland Zloty"},
    {value: "QAR", label: "Qatar Riyal"},
    {value: "RON", label: "Romania Leu"},
    {value: "RUB", label: "Russia Ruble"},
    {value: "RWF", label: "Rwanda Franc"},
    {value: "SHP", label: "Saint Helena Pound"},
    {value: "WST", label: "Samoa Tala"},
    {value: "STN", label: "São Tomé and Príncipe Dobra"},
    {value: "SAR", label: "Saudi Arabia Riyal"},
    {value: "SPL*", label: "Seborga Luigino"},
    {value: "RSD", label: "Serbia Dinar"},
    {value: "SCR", label: "Seychelles Rupee"},
    {value: "SLL", label: "Sierra Leone Leone"},
    {value: "SGD", label: "Singapore Dollar"},
    {value: "SBD", label: "Solomon Islands Dollar"},
    {value: "SOS", label: "Somalia Shilling"},
    {value: "ZAR", label: "South Africa Rand"},
    {value: "LKR", label: "Sri Lanka Rupee"},
    {value: "SDG", label: "Sudan Pound"},
    {value: "SRD", label: "Suriname Dollar"},
    {value: "SEK", label: "Sweden Krona"},
    {value: "CHF", label: "Switzerland Franc"},
    {value: "SYP", label: "Syria Pound"},
    {value: "TWD", label: "Taiwan New Dollar"},
    {value: "TJS", label: "Tajikistan Somoni"},
    {value: "TZS", label: "Tanzania Shilling"},
    {value: "THB", label: "Thailand Baht"},
    {value: "TOP", label: "Tonga Pa'anga"},
    {value: "TTD", label: "Trinidad and Tobago Dollar"},
    {value: "TND", label: "Tunisia Dinar"},
    {value: "TRY", label: "Turkey Lira"},
    {value: "TMT", label: "Turkmenistan Manat"},
    {value: "TVD", label: "Tuvalu Dollar"},
    {value: "UGX", label: "Uganda Shilling"},
    {value: "UAH", label: "Ukraine Hryvnia"},
    {value: "AED", label: "United Arab Emirates Dirham"},
    {value: "GBP", label: "United Kingdom Pound"},
    {value: "USD", label: "United States Dollar"},
    {value: "UYU", label: "Uruguay Peso"},
    {value: "UZS", label: "Uzbekistan Som"},
    {value: "VUV", label: "Vanuatu Vatu"},
    {value: "VEF", label: "Venezuela Bolívar"},
    {value: "VND", label: "Viet Nam Dong"},
    {value: "YER", label: "Yemen Rial"},
    {value: "ZMW", label: "Zambia Kwacha"},
    {value: "ZWD", label: "Zimbabwe Dollar"}
  ]

  static countryCodes = [
    {value: "AF", label: "Afghanistan"},
    {value: "AX", label: "Åland Islands"},
    {value: "AL", label: "Albania"},
    {value: "DZ", label: "Algeria"},
    {value: "AS", label: "American Samoa"},
    {value: "AD", label: "Andorra"},
    {value: "AO", label: "Angola"},
    {value: "AI", label: "Anguilla"},
    {value: "AQ", label: "Antarctica"},
    {value: "AG", label: "Antigua and Barbuda"},
    {value: "AR", label: "Argentina"},
    {value: "AM", label: "Armenia"},
    {value: "AW", label: "Aruba"},
    {value: "AU", label: "Australia"},
    {value: "AT", label: "Austria"},
    {value: "AZ", label: "Azerbaijan"},
    {value: "BS", label: "Bahamas"},
    {value: "BH", label: "Bahrain"},
    {value: "BD", label: "Bangladesh"},
    {value: "BB", label: "Barbados"},
    {value: "BY", label: "Belarus"},
    {value: "BE", label: "Belgium"},
    {value: "BZ", label: "Belize"},
    {value: "BJ", label: "Benin"},
    {value: "BM", label: "Bermuda"},
    {value: "BT", label: "Bhutan"},
    {value: "BO", label: "Bolivia (Plurinational State of)"},
    {value: "BQ", label: "Bonaire, Sint Eustatius and Saba"},
    {value: "BA", label: "Bosnia and Herzegovina"},
    {value: "BW", label: "Botswana"},
    {value: "BV", label: "Bouvet Island"},
    {value: "BR", label: "Brazil"},
    {value: "IO", label: "British Indian Ocean Territory"},
    {value: "BN", label: "Brunei Darussalam"},
    {value: "BG", label: "Bulgaria"},
    {value: "BF", label: "Burkina Faso"},
    {value: "BI", label: "Burundi"},
    {value: "CV", label: "Cabo Verde"},
    {value: "KH", label: "Cambodia"},
    {value: "CM", label: "Cameroon"},
    {value: "CA", label: "Canada"},
    {value: "KY", label: "Cayman Islands"},
    {value: "CF", label: "Central African Republic"},
    {value: "TD", label: "Chad"},
    {value: "CL", label: "Chile"},
    {value: "CN", label: "China"},
    {value: "CX", label: "Christmas Island"},
    {value: "CC", label: "Cocos (Keeling) Islands"},
    {value: "CO", label: "Colombia"},
    {value: "KM", label: "Comoros"},
    {value: "CG", label: "Congo"},
    {value: "CD", label: "Congo, Democratic Republic of the"},
    {value: "CK", label: "Cook Islands"},
    {value: "CR", label: "Costa Rica"},
    {value: "CI", label: "Côte d'Ivoire"},
    {value: "HR", label: "Croatia"},
    {value: "CU", label: "Cuba"},
    {value: "CW", label: "Curaçao"},
    {value: "CY", label: "Cyprus"},
    {value: "CZ", label: "Czechia"},
    {value: "DK", label: "Denmark"},
    {value: "DJ", label: "Djibouti"},
    {value: "DM", label: "Dominica"},
    {value: "DO", label: "Dominican Republic"},
    {value: "EC", label: "Ecuador"},
    {value: "EG", label: "Egypt"},
    {value: "SV", label: "El Salvador"},
    {value: "GQ", label: "Equatorial Guinea"},
    {value: "ER", label: "Eritrea"},
    {value: "EE", label: "Estonia"},
    {value: "SZ", label: "Eswatini"},
    {value: "ET", label: "Ethiopia"},
    {value: "FK", label: "Falkland Islands (Malvinas)"},
    {value: "FO", label: "Faroe Islands"},
    {value: "FJ", label: "Fiji"},
    {value: "FI", label: "Finland"},
    {value: "FR", label: "France"},
    {value: "GF", label: "French Guiana"},
    {value: "PF", label: "French Polynesia"},
    {value: "TF", label: "French Southern Territories"},
    {value: "GA", label: "Gabon"},
    {value: "GM", label: "Gambia"},
    {value: "GE", label: "Georgia"},
    {value: "DE", label: "Germany"},
    {value: "GH", label: "Ghana"},
    {value: "GI", label: "Gibraltar"},
    {value: "GR", label: "Greece"},
    {value: "GL", label: "Greenland"},
    {value: "GD", label: "Grenada"},
    {value: "GP", label: "Guadeloupe"},
    {value: "GU", label: "Guam"},
    {value: "GT", label: "Guatemala"},
    {value: "GG", label: "Guernsey"},
    {value: "GN", label: "Guinea"},
    {value: "GW", label: "Guinea-Bissau"},
    {value: "GY", label: "Guyana"},
    {value: "HT", label: "Haiti"},
    {value: "HM", label: "Heard Island and McDonald Islands"},
    {value: "VA", label: "Holy See"},
    {value: "HN", label: "Honduras"},
    {value: "HK", label: "Hong Kong"},
    {value: "HU", label: "Hungary"},
    {value: "IS", label: "Iceland"},
    {value: "IN", label: "India"},
    {value: "ID", label: "Indonesia"},
    {value: "IR", label: "Iran (Islamic Republic of)"},
    {value: "IQ", label: "Iraq"},
    {value: "IE", label: "Ireland"},
    {value: "IM", label: "Isle of Man"},
    {value: "IL", label: "Israel"},
    {value: "IT", label: "Italy"},
    {value: "JM", label: "Jamaica"},
    {value: "JP", label: "Japan"},
    {value: "JE", label: "Jersey"},
    {value: "JO", label: "Jordan"},
    {value: "KZ", label: "Kazakhstan"},
    {value: "KE", label: "Kenya"},
    {value: "KI", label: "Kiribati"},
    {value: "KP", label: "Korea (Democratic People's Republic of)"},
    {value: "KR", label: "Korea, Republic of"},
    {value: "KW", label: "Kuwait"},
    {value: "KG", label: "Kyrgyzstan"},
    {value: "LA", label: "Lao People's Democratic Republic"},
    {value: "LV", label: "Latvia"},
    {value: "LB", label: "Lebanon"},
    {value: "LS", label: "Lesotho"},
    {value: "LR", label: "Liberia"},
    {value: "LY", label: "Libya"},
    {value: "LI", label: "Liechtenstein"},
    {value: "LT", label: "Lithuania"},
    {value: "LU", label: "Luxembourg"},
    {value: "MO", label: "Macao"},
    {value: "MK", label: "Macedonia, the former Yugoslav Republic of"},
    {value: "MG", label: "Madagascar"},
    {value: "MW", label: "Malawi"},
    {value: "MY", label: "Malaysia"},
    {value: "MV", label: "Maldives"},
    {value: "ML", label: "Mali"},
    {value: "MT", label: "Malta"},
    {value: "MH", label: "Marshall Islands"},
    {value: "MQ", label: "Martinique"},
    {value: "MR", label: "Mauritania"},
    {value: "MU", label: "Mauritius"},
    {value: "YT", label: "Mayotte"},
    {value: "MX", label: "Mexico"},
    {value: "FM", label: "Micronesia (Federated States of)"},
    {value: "MD", label: "Moldova, Republic of"},
    {value: "MC", label: "Monaco"},
    {value: "MN", label: "Mongolia"},
    {value: "ME", label: "Montenegro"},
    {value: "MS", label: "Montserrat"},
    {value: "MA", label: "Morocco"},
    {value: "MZ", label: "Mozambique"},
    {value: "MM", label: "Myanmar"},
    {value: "NA", label: "Namibia"},
    {value: "NR", label: "Nauru"},
    {value: "NP", label: "Nepal"},
    {value: "NL", label: "Netherlands"},
    {value: "NC", label: "New Caledonia"},
    {value: "NZ", label: "New Zealand"},
    {value: "NI", label: "Nicaragua"},
    {value: "NE", label: "Niger"},
    {value: "NG", label: "Nigeria"},
    {value: "NU", label: "Niue"},
    {value: "NF", label: "Norfolk Island"},
    {value: "MP", label: "Northern Mariana Islands"},
    {value: "NO", label: "Norway"},
    {value: "OM", label: "Oman"},
    {value: "PK", label: "Pakistan"},
    {value: "PW", label: "Palau"},
    {value: "PS", label: "Palestine, State of"},
    {value: "PA", label: "Panama"},
    {value: "PG", label: "Papua New Guinea"},
    {value: "PY", label: "Paraguay"},
    {value: "PE", label: "Peru"},
    {value: "PH", label: "Philippines"},
    {value: "PN", label: "Pitcairn"},
    {value: "PL", label: "Poland"},
    {value: "PT", label: "Portugal"},
    {value: "PR", label: "Puerto Rico"},
    {value: "QA", label: "Qatar"},
    {value: "RE", label: "Réunion"},
    {value: "RO", label: "Romania"},
    {value: "RU", label: "Russian Federation"},
    {value: "RW", label: "Rwanda"},
    {value: "BL", label: "Saint Barthélemy"},
    {value: "SH", label: "Saint Helena, Ascension and Tristan da Cunha"},
    {value: "KN", label: "Saint Kitts and Nevis"},
    {value: "LC", label: "Saint Lucia"},
    {value: "MF", label: "Saint Martin (French part)"},
    {value: "PM", label: "Saint Pierre and Miquelon"},
    {value: "VC", label: "Saint Vincent and the Grenadines"},
    {value: "WS", label: "Samoa"},
    {value: "SM", label: "San Marino"},
    {value: "ST", label: "Sao Tome and Principe"},
    {value: "SA", label: "Saudi Arabia"},
    {value: "SN", label: "Senegal"},
    {value: "RS", label: "Serbia"},
    {value: "SC", label: "Seychelles"},
    {value: "SL", label: "Sierra Leone"},
    {value: "SG", label: "Singapore"},
    {value: "SX", label: "Sint Maarten (Dutch part)"},
    {value: "SK", label: "Slovakia"},
    {value: "SI", label: "Slovenia"},
    {value: "SB", label: "Solomon Islands"},
    {value: "SO", label: "Somalia"},
    {value: "ZA", label: "South Africa"},
    {value: "GS", label: "South Georgia and the South Sandwich Islands"},
    {value: "SS", label: "South Sudan"},
    {value: "ES", label: "Spain"},
    {value: "LK", label: "Sri Lanka"},
    {value: "SD", label: "Sudan"},
    {value: "SR", label: "Suriname"},
    {value: "SJ", label: "Svalbard and Jan Mayen"},
    {value: "SE", label: "Sweden"},
    {value: "CH", label: "Switzerland"},
    {value: "SY", label: "Syrian Arab Republic"},
    {value: "TW", label: "Taiwan, Province of China"},
    {value: "TJ", label: "Tajikistan"},
    {value: "TZ", label: "Tanzania, United Republic of"},
    {value: "TH", label: "Thailand"},
    {value: "TL", label: "Timor-Leste"},
    {value: "TG", label: "Togo"},
    {value: "TK", label: "Tokelau"},
    {value: "TO", label: "Tonga"},
    {value: "TT", label: "Trinidad and Tobago"},
    {value: "TN", label: "Tunisia"},
    {value: "TR", label: "Turkey"},
    {value: "TM", label: "Turkmenistan"},
    {value: "TC", label: "Turks and Caicos Islands"},
    {value: "TV", label: "Tuvalu"},
    {value: "UG", label: "Uganda"},
    {value: "UA", label: "Ukraine"},
    {value: "AE", label: "United Arab Emirates"},
    {value: "GB", label: "United Kingdom of Great Britain and Northern Ireland"},
    {value: "UM", label: "United States Minor Outlying Islands"},
    {value: "US", label: "United States of America"},
    {value: "UY", label: "Uruguay"},
    {value: "UZ", label: "Uzbekistan"},
    {value: "VU", label: "Vanuatu"},
    {value: "VE", label: "Venezuela (Bolivarian Republic of)"},
    {value: "VN", label: "Viet Nam"},
    {value: "VG", label: "Virgin Islands (British)"},
    {value: "VI", label: "Virgin Islands (U.S.)"},
    {value: "WF", label: "Wallis and Futuna"},
    {value: "EH", label: "Western Sahara"},
    {value: "YE", label: "Yemen"},
    {value: "ZM", label: "Zambia"},
    {value: "ZW", label: "Zimbabwe"},
  ]

  static organisationCodes = [
    {value: 10, label: "Government"},
    {value: 11, label: "Local Government"},
    {value: 15, label: "Other Public Sector"},
    {value: 21, label: "International NGO"},
    {value: 22, label: "National NGO"},
    {value: 23, label: "Regional NGO"},
    {value: 24, label: "Partner Country based NGO"},
    {value: 30, label: "Public Private Partnership"},
    {value: 40, label: "Multilateral"},
    {value: 60, label: "Foundation"},
    {value: 70, label: "Private Sector"},
    {value: 71, label: "Private Sector in Provider Country"},
    {value: 72, label: "Private Sector in Aid Recipient Country"},
    {value: 73, label: "Private Sector in Third Country"},
    {value: 80, label: "Academic, Training and Research"},
    {value: 90, label: "Other"}
  ]

  static oecdDacCrs = [
    {value: 1, label: "Austria"},
    {value: 2, label: "Belgium"},
    {value: 3, label: "Denmark"},
    {value: 4, label: "France"},
    {value: 5, label: "Germany"},
    {value: 6, label: "Italy"},
    {value: 7, label: "Netherlands"},
    {value: 8, label: "Norway"},
    {value: 9, label: "Portugal"},
    {value: 10, label: "Sweden"},
    {value: 11, label: "Switzerland"},
    {value: 12, label: "United Kingdom"},
    {value: 18, label: "Finland"},
    {value: 20, label: "Iceland"},
    {value: 21, label: "Ireland"},
    {value: 22, label: "Luxembourg"},
    {value: 30, label: "Cyprus"},
    {value: 40, label: "Greece"},
    {value: 45, label: "Malta"},
    {value: 50, label: "Spain"},
    {value: 55, label: "Turkey"},
    {value: 61, label: "Slovenia"},
    {value: 62, label: "Croatia"},
    {value: 68, label: "Czech Republic"},
    {value: 69, label: "Slovak Republic"},
    {value: 70, label: "Liechtenstein"},
    {value: 72, label: "Bulgaria"},
    {value: 75, label: "Hungary"},
    {value: 76, label: "Poland"},
    {value: 77, label: "Romania"},
    {value: 82, label: "Estonia"},
    {value: 83, label: "Latvia"},
    {value: 84, label: "Lithuania"},
    {value: 87, label: "Russia"},
    {value: 104, label: "Nordic Development Fund"},
    {value: 130, label: "Algeria"},
    {value: 133, label: "Libya"},
    {value: 301, label: "Canada"},
    {value: 302, label: "United States"},
    {value: 358, label: "Mexico"},
    {value: 543, label: "Iraq"},
    {value: 546, label: "Israel"},
    {value: 552, label: "Kuwait"},
    {value: 561, label: "Qatar"},
    {value: 566, label: "Saudi Arabia"},
    {value: 576, label: "United Arab Emirates"},
    {value: 611, label: "Azerbaijan"},
    {value: 613, label: "Kazakhstan"},
    {value: 701, label: "Japan"},
    {value: 732, label: "Chinese Taipei"},
    {value: 742, label: "Korea"},
    {value: 764, label: "Thailand"},
    {value: 765, label: "Timor-Leste"},
    {value: 801, label: "Australia"},
    {value: 807, label: "UNEP"},
    {value: 811, label: "Global Environment Facility"},
    {value: 812, label: "Montreal Protocol"},
    {value: 820, label: "New Zealand"},
    {value: 901, label: "International Bank for Reconstruction and Development"},
    {value: 902, label: "Multilateral Investment Guarantee Agency"},
    {value: 903, label: "International Finance Corporation"},
    {value: 905, label: "International Development Association"},
    {value: 906, label: "Caribbean Development Bank"},
    {value: 907, label: "International Monetary Fund"},
    {value: 909, label: "Inter-American Development Bank"},
    {value: 912, label: "IDB Special Fund"},
    {value: 913, label: "African Development Bank"},
    {value: 914, label: "African Development Fund"},
    {value: 915, label: "Asian Development Bank"},
    {value: 916, label: "AsDB Special Funds"},
    {value: 918, label: "EU Institutions"},
    {value: 921, label: "Arab Fund (AFESD)"},
    {value: 923, label: "UN Peacebuilding Fund"},
    {value: 926, label: "Council of Europe"},
    {value: 928, label: "World Health Organisation"},
    {value: 932, label: "Food and Agriculture Organisation"},
    {value: 940, label: "International Labour Organisation"},
    {value: 944, label: "International Atomic Energy Agency"},
    {value: 948, label: "UNECE"},
    {value: 951, label: "OPEC Fund for International Development"},
    {value: 952, label: "OAPEC"},
    {value: 953, label: "Arab Bank for Economic Development in Africa"},
    {value: 954, label: "Special Arab Aid Fund for Africa"},
    {value: 956, label: "IMF Trust Fund"},
    {value: 958, label: "IMF (Concessional Trust Funds)"},
    {value: 959, label: "UNDP"},
    {value: 960, label: "UNTA"},
    {value: 963, label: "UNICEF"},
    {value: 964, label: "UNRWA"},
    {value: 966, label: "WFP"},
    {value: 967, label: "UNHCR"},
    {value: 971, label: "UNAIDS"},
    {value: 974, label: "UNFPA"},
    {value: 976, label: "Islamic Development Bank"},
    {value: 978, label: "OSCE"},
    {value: 979, label: "Islamic Monetary Fund"},
    {value: 980, label: "Arab Fund for Technical Assistance to African and Arab Countries"},
    {value: 981, label: "Black Sea Trade & Development Bank"},
    {value: 982, label: "GODE"},
    {value: 983, label: "Other Arab Agencies"},
    {value: 988, label: "IFAD"},
    {value: 990, label: "European Bank for Reconstruction and Development"},
    {value: 992, label: "UN AGENCIES"},
    {value: 997, label: "Global Partnership for Education"},
    {value: 1011, label: "Climate Investment Funds"},
    {value: 1012, label: "Adaptation Fund"},
    {value: 1013, label: "Council of Europe Development Bank"},
    {value: 1014, label: "Private Infrastructure Development Group"},
    {value: 1015, label: "Development Bank of Latin America"},
    {value: 1016, label: "Green Climate Fund"},
    {value: 1017, label: "Credit Guarantee and Investment Facility"},
    {value: 1018, label: "Global Energy Efficiency and Renewable Energy Fund"},
    {value: 1019, label: "IDB Invest"},
    {value: 1020, label: "Central Emergency Response Fund"},
    {value: 1023, label: "World Tourism Organisation"},
    {value: 1024, label: "Asian Infrastructure Investment Bank"},
    {value: 1025, label: "Center of Excellence in Finance"},
    {value: 1311, label: "Global Alliance for Vaccines and Immunization"},
    {value: 1312, label: "Global Fund"},
    {value: 1313, label: "Global Green Growth Institute"},
    {value: 1601, label: "Bill & Melinda Gates Foundation"},
    {value: 1602, label: "Dutch Postcode Lottery"},
    {value: 1603, label: "Swedish Postcode Lottery"},
    {value: 1604, label: "People's Postcode Lottery"},
    {value: 1605, label: "MetLife Foundation"},
    {value: 1606, label: "MasterCard Foundation"},
    {value: 1607, label: "Grameen Crédit Agricole Foundation"},
    {value: 1608, label: "IKEA Foundation"},
    {value: 1609, label: "Bernard van Leer Foundation"},
    {value: 1610, label: "MAVA Foundation"},
    {value: 1611, label: "Oak Foundation"},
    {value: 1612, label: "H&M Foundation"},
    {value: 1613, label: "C&A Foundation"},
    {value: 1614, label: "Charity Projects Ltd (Comic Relief)"},
    {value: 1615, label: "Children's Investment Fund Foundation"},
    {value: 1616, label: "Gatsby Charitable Foundation"},
    {value: 1617, label: "Conrad N. Hilton Foundation"},
    {value: 1618, label: "David & Lucile Packard Foundation"},
    {value: 1619, label: "John D. & Catherine T. MacArthur Foundation"},
    {value: 1620, label: "Carnegie Corporation of New York"},
    {value: 1621, label: "Michael & Susan Dell Foundation"},
    {value: 1622, label: "Omidyar Network Fund, Inc."},
    {value: 1623, label: "Rockefeller Foundation"},
    {value: 1624, label: "William & Flora Hewlett Foundation"},
    {value: 1625, label: "Arcus Foundation"},
    {value: 1626, label: "Gordon and Betty Moore Foundation"},
    {value: 1627, label: "Ford Foundation"},
    {value: 1628, label: "Wellcome Trust"}
  ]

  static financeStatus = [
    {value: 1, label:	"Indicative"},
    {value: 2, label:	"Committed"}
  ]

  static days = [
    {value: 1, label: "1"},
    {value: 2, label: "2"},
    {value: 3, label: "3"},
    {value: 4, label: "4"},
    {value: 5, label: "5"},
    {value: 6, label: "6"},
    {value: 7, label: "7"},
    {value: 8, label: "8"},
    {value: 9, label: "9"},
    {value: 10, label: "10"},
    {value: 11, label: "11"},
    {value: 12, label: "12"},
    {value: 13, label: "13"},
    {value: 14, label: "14"},
    {value: 15, label: "15"},
    {value: 16, label: "16"},
    {value: 17, label: "17"},
    {value: 18, label: "18"},
    {value: 19, label: "19"},
    {value: 20, label: "20"},
    {value: 21, label: "21"},
    {value: 22, label: "22"},
    {value: 23, label: "23"},
    {value: 24, label: "24"},
    {value: 25, label: "25"},
    {value: 26, label: "26"},
    {value: 27, label: "27"},
    {value: 28, label: "28"},
    {value: 29, label: "29"},
    {value: 30, label: "30"},
    {value: 31, label: "31"}
  ]

  static months = [
    {value: 1, label: "January"},
    {value: 2, label: "February"},
    {value: 3, label: "March"},
    {value: 4, label: "April"},
    {value: 5, label: "May"},
    {value: 6, label: "June"},
    {value: 7, label: "July"},
    {value: 8, label: "August"},
    {value: 9, label: "September"},
    {value: 10, label: "October"},
    {value: 11, label: "November"},
    {value: 12, label: "December"}
  ]

  static years = [
    {value: 2000, label: "2000"},
    {value: 2001, label: "2001"},
    {value: 2002, label: "2002"},
    {value: 2003, label: "2003"},
    {value: 2004, label: "2004"},
    {value: 2005, label: "2005"},
    {value: 2006, label: "2006"},
    {value: 2007, label: "2007"},
    {value: 2008, label: "2008"},
    {value: 2009, label: "2009"},
    {value: 2010, label: "2010"},
    {value: 2011, label: "2011"},
    {value: 2012, label: "2012"},
    {value: 2013, label: "2013"},
    {value: 2014, label: "2014"},
    {value: 2015, label: "2015"},
    {value: 2016, label: "2016"},
    {value: 2017, label: "2017"},
    {value: 2018, label: "2018"},
    {value: 2019, label: "2019"},
    {value: 2020, label: "2020"},
    {value: 2021, label: "2021"},
    {value: 2022, label: "2022"},
    {value: 2023, label: "2023"},
    {value: 2024, label: "2024"},
    {value: 2025, label: "2025"},
    {value: 2026, label: "2026"},
    {value: 2027, label: "2027"},
    {value: 2028, label: "2028"},
    {value: 2029, label: "2029"},
    {value: 2030, label: "2030"},
    {value: 2031, label: "2031"},
    {value: 2032, label: "2032"},
    {value: 2033, label: "2033"},
    {value: 2034, label: "2034"},
    {value: 2035, label: "2035"},
    {value: 2036, label: "2036"},
    {value: 2037, label: "2037"},
    {value: 2038, label: "2038"},
    {value: 2039, label: "2039"},
    {value: 2040, label: "2040"}
  ]

}

export { Paths, Blockchain, Contract, Helpers }
