export interface OrganisationReportProps {
  organisationsRef: string
}

export interface OrganisationsReportProps {
 organisationsRef: string
 organisationRef: string
}

export const enum IATIReportActionTypes {
  ORGS_SUCCESS = '@@IATIReportActionTypes/READORGS_SUCCESS',
  ORGS_FAILURE = '@@IATIReportActionTypes/READORGS_FAILURE',
  ORGANISATIONS_SUCCESS = '@@IATIReportActionTypes/READORGANISATIONS_SUCCESS',
  ORGANISATIONS_FAILURE = '@@IATIReportActionTypes/READORGANISATIONS_FAILURE',
  ORGANISATION_SUCCESS = '@@IATIReportActionTypes/READORGANISATION_SUCCESS',
  ORGANISATION_FAILURE = '@@IATIReportActionTypes/READORGANISATION_FAILURE',
  BUDGET_SUCCESS = '@@IATIReportActionTypes/READBUDGET_SUCCESS',
  BUDGET_FAILURE = '@@IATIReportActionTypes/READBUDGET_FAILURE',
  RECIPIENTORGBUDGET_SUCCESS = '@@IATIReportActionTypes/READRECIPIENTORGBUDGET_SUCCESS',
  RECIPIENTORGBUDGET_FAILURE = '@@IATIReportActionTypes/READRECIPIENTORGBUDGET_FAILURE',
  RECIPIENTREGIONBUDGET_SUCCESS = '@@IATIReportActionTypes/READRECIPIENTREGIONBUDGET_SUCCESS',
  RECIPIENTREGIONBUDGET_FAILURE = '@@IATIReportActionTypes/READRECIPIENTREGIONBUDGET_FAILURE',
  RECIPIENTCOUNTRYBUDGET_SUCCESS = '@@IATIReportActionTypes/READRECIPIENTCOUNTRYBUDGET_SUCCESS',
  RECIPIENTCOUNTRYBUDGET_FAILURE = '@@IATIReportActionTypes/READRECIPIENTCOUNTRYBUDGET_FAILURE',
  TOTALEXPENDITURE_SUCCESS = '@@IATIReportActionTypes/READTOTALEXPENDITURE_SUCCESS',
  TOTALEXPENDITURE_FAILURE = '@@IATIReportActionTypes/READTOTALEXPENDITURE_FAILURE',
  DOCUMENT_SUCCESS = '@@IATIReportActionTypes/READDOCUMENT_SUCCESS',
  DOCUMENT_FAILURE = '@@IATIReportActionTypes/READDOCUMENT_FAILURE'
}
