interface FinanceProps {
  value: number
  status: number
  start: string
  end: string
}

export interface IATIBudgetProps {
  budgetType: number
  budgetLine: string
  otherRef: string
  finance: FinanceProps
}

export const enum IATIWriterActionTypes{
  TX_INIT =  '@@IATIWriterActionTypes/TX_INIT',
  ORGS_SUCCESS = '@@IATIWriterActionTypes/ORGS_SUCCESS',
  ORGS_FAILURE = '@@IATIWriterActionTypes/ORGS_FAILURE',
  ORGANISATIONS_SUCCESS = '@@IATIWriterActionTypes/ORGANISATIONS_SUCCESS',
  ORGANISATIONS_FAILURE = '@@IATIWriterActionTypes/ORGANISATIONS_FAILURE',
  ORGANISATION_SUCCESS = '@@IATIWriterActionTypes/ORGANISATION_SUCCESS',
  ORGANISATION_FAILURE = '@@IATIWriterActionTypes/ORGANISATION_FAILURE',
  BUDGET_SUCCESS = '@@IATIWriterActionTypes/BUDGET_SUCCESS',
  BUDGET_FAILURE = '@@IATIWriterActionTypes/BUDGET_FAILURE',
  RECIPIENTORGBUDGET_SUCCESS = '@@IATIWriterActionTypes/RECIPIENTORGBUDGET_SUCCESS',
  RECIPIENTORGBUDGET_FAILURE = '@@IATIWriterActionTypes/RECIPIENTORGBUDGET_FAILURE',
  RECIPIENTREGIONBUDGET_SUCCESS = '@@IATIWriterActionTypes/RECIPIENTREGIONBUDGET_SUCCESS',
  RECIPIENTREGIONBUDGET_FAILURE = '@@IATIWriterActionTypes/RECIPIENTREGIONBUDGET_FAILURE',
  RECIPIENTCOUNTRYBUDGET_SUCCESS = '@@IATIWriterActionTypes/RECIPIENTCOUNTRYBUDGET_SUCCESS',
  RECIPIENTCOUNTRYBUDGET_FAILURE = '@@IATIWriterActionTypes/RECIPIENTCOUNTRYBUDGET_FAILURE',
  TOTALEXPENDITURE_SUCCESS = '@@IATIWriterActionTypes/TOTALEXPENDITURE_SUCCESS',
  TOTALEXPENDITURE_FAILURE = '@@IATIWriterActionTypes/TOTALEXPENDITURE_FAILURE',
  DOCUMENT_SUCCESS = '@@IATIWriterActionTypes/DOCUMENT_SUCCESS',
  DOCUMENT_FAILURE = '@@IATIWriterActionTypes/DOCUMENT_FAILURE',
  ACTIVITIES_SUCCESS = '@@IATIWriterActionTypes/ACTIVITIES_SUCCESS',
  ACTIVITIES_FAILURE = '@@IATIWriterActionTypes/ACTIVITIES_FAILURE'  
}
