---
title: "Humanitarian Aid Reporting: An Application of Blockchains"
author: "Steve Huckle"
header-includes:
    - \usepackage{fancyhdr}
    - \pagestyle{fancy}
    - \lhead{\thepage}
    - \chead{}
    - \rhead{}
    - \lfoot{© 2020 — University of Sussex, Department of Informatics}
    - \cfoot{}
    - \rfoot{}
    - \renewcommand{\headrulewidth}{0.4pt}
    - \renewcommand{\footrulewidth}{0.4pt}
---
